#ifndef SYSTEMLOG_OPERID_H
#define SYSTEMLOG_OPERID_H

enum SYSTEMLOG_PAGEID
{
	SYSTEMLOG_PAGE_MAIN = 1, //主界面
	SYSTEMLOG_PAGE_FRONTMAIN, //前端界面
	SYSTEMLOG_PAGE_BACKMAIN, //后端界面
	SYSTEMLOG_PAGE_VIDEO, //播放界面
	SYSTEMLOG_PAGE_MEETINGFILE, //会议资料界面
	SYSTEMLOG_PAGE_MEETINGAGEND, //会议议程界面
	SYSTEMLOG_PAGE_MEETINGNOTE, //查看批注界面
	SYSTEMLOG_PAGE_DOWNLOAD, //下载界面
	SYSTEMLOG_PAGE_UPLOAD, //上传界面
	SYSTEMLOG_PAGE_WHITEBOARD, //白板界面
	SYSTEMLOG_PAGE_DOCUMENT,//文档界面(office)
	SYSTEMLOG_PAGE_BACKPREMEETMANAGEMENT,//后台->会前->会议管理
	SYSTEMLOG_PAGE_BACKPREMEETFILE,//后台->会前->会议资料
	SYSTEMLOG_PAGE_BACKMIDVOTE,//后台->会中->投票管理
	SYSTEMLOG_PAGE_BACKMIDELECTION,//后台->会中->选举管理
	SYSTEMLOG_PAGE_BACKMIDCAMERA,//后台->会中->摄像机控制
	SYSTEMLOG_PAGE_BACKMIDSCREEN,//后台->会中->屏幕管理
	SYSTEMLOG_PAGE_BACKENDNOTATION,//后台->会后->批注查看
	SYSTEMLOG_PAGE_SECVOTEMANAGEMENT,//前端->秘书管理->投票管理
	SYSTEMLOG_PAGE_SECELECTORALMANAGEMENT,//前端->秘书管理->选举管理
	SYSTEMLOG_PAGE_SECVIDEOCONTROL,//前端->秘书管理->视频管理
	SYSTEMLOG_PAGE_LOGON, //登陆界面
	SYSTEMLOG_PAGE_BACKMEMBER, //参会人界面
	SYSTEMLOG_PAGE_BACKPEOPLE, //常用人员界面
	SYSTEMLOG_PAGE_BACKADMIN, //管理界面
	SYSTEMLOG_PAGE_BACKROOM, //会场管理界面
	SYSTEMLOG_PAGE_ROOMSET, //会场布局界面
	SYSTEMLOG_PAGE_PREVOTE, //会前投票界面
	SYSTEMLOG_PAGE_MIDVOTE, //会中投票界面
	SYSTEMLOG_PAGE_SIGNUP, //会后签到界面
	
	SYSTEMLOG_PAGE_TABLECARD, //会后桌牌界面
	SYSTEMLOG_PAGE_CACHE, //缓存文件界面
	SYSTEMLOG_PAGE_ARCHIVERE, //后台-会后-归档界面
	SYSTEMLOG_PAGE_VIDEORECORD, //后台-会后-录像查看
};

//日志统计操作ID 用于标识会议中的业务操作,已经定义的值，请不要变更，不要数据库中的数据会解析错误，数据日志记录会自动删除30天之前的,可以自行添加日志操作的定义
enum SYSTEMLOG_OPERID 
{
	SYSTEMLOG_OPER_SCREENSHARE = 1, //桌面同屏
	SYSTEMLOG_OPER_FILESCREENSHARE,//文件同屏（param[0]=fileid）
	SYSTEMLOG_OPER_OPENFILE, //查看文件（param[0]=fileid）
	SYSTEMLOG_OPER_OPENVIDEOSTREAM, //查看流  （param[0]=device,param[1]=subid）
	SYSTEMLOG_OPER_SCREENVIDEOSTREAM,//同屏视频流  （param[0]=device,param[1]=subid）
	SYSTEMLOG_OPER_UPLOADFILE,//上传文件（param[0]=fileid,param[1]=dirid）
	SYSTEMLOG_OPER_DOWNLOADFILE,//下载文件（param[0]=fileid,param[1]=dirid）
	SYSTEMLOG_OPER_DELETEFILE,//删除文件（param[0]=fileid,param[1]=dirid）
	SYSTEMLOG_OPER_MODIFYFILE,//修改文件（param[0]=fileid,param[1]=dirid）
	SYSTEMLOG_OPER_ENTERMEET,//进入会议
	SYSTEMLOG_OPER_EXITMEET,//退出会议
	SYSTEMLOG_OPER_STARTVOTE,//开始投票（param[0]=voteid）
	SYSTEMLOG_OPER_SUBMITVOTE,//提交投票（param[0]=voteid）
	SYSTEMLOG_OPER_STOPVOTE,//停止投票（param[0]=voteid）
	SYSTEMLOG_OPER_STOPPLAY,//停止播放媒体（param[0]=fileid）
	SYSTEMLOG_OPER_STOPSCREENSHARE,//停止同屏（param[0]=device,param[1]=subid）
	SYSTEMLOG_OPER_STOPPROJECTFILE,//停止投影文件（param[0]=fileid）
	SYSTEMLOG_OPER_STOPPROJECTSTREAM,//停止投影流（param[0]=device,param[1]=subid）
	SYSTEMLOG_OPER_STARTPROJECTFILE,//投影文件（param[0]=fileid,param[1]=dirid）
	SYSTEMLOG_OPER_STARTPROJECTSTREAM,//投影流（param[0]=device,param[1]=subid）
	SYSTEMLOG_OPER_ADMINLOGON,//管理员登陆
	SYSTEMLOG_OPER_ADMINLOGOUT,//管理员退出
	SYSTEMLOG_OPER_STARTWHITEBOARD,//开始白板
	SYSTEMLOG_OPER_ENTERWHITEBOARD,//进入白板
	SYSTEMLOG_OPER_REJECTWHITEBOARD,//拒绝加入白板
	SYSTEMLOG_OPER_EXITWHITEBOARD,//退出白板
	SYSTEMLOG_OPER_JOINSCREEN,//加入同屏
	SYSTEMLOG_OPER_STARTMUTILPOSTIL,//开始多人书写
	SYSTEMLOG_OPER_ENTERMUTILPOSTIL,//进入多人书写
	SYSTEMLOG_OPER_REJECTMUTILPOSTIL,//拒绝加入多人书写
	SYSTEMLOG_OPER_EXITMUTILPOSTIL,//退出多人书写
	SYSTEMLOG_OPER_SCREENSHOT,//桌面截图
	SYSTEMLOG_OPER_SCANDOWNLOAD,//扫描下载
	SYSTEMLOG_OPER_SAVELOCAL,//保存文件到本地
	SYSTEMLOG_OPER_SAVESERVER,//保存文件到服务器
	SYSTEMLOG_OPER_SHOTPOSTIL,//截图批注
	SYSTEMLOG_OPER_QUERYMEET,//查询会议
	SYSTEMLOG_OPER_ADDMEET,//添加会议
	SYSTEMLOG_OPER_MODIFYMEET,//修改会议
	SYSTEMLOG_OPER_DELETEMEET,//删除会议
	SYSTEMLOG_OPER_STARTMEET,//开始会议
	SYSTEMLOG_OPER_PAUSEMEET,//暂停会议
	SYSTEMLOG_OPER_STOPEMEET,//结束会议
	SYSTEMLOG_OPER_DUMPMEET,//复制会议
	SYSTEMLOG_OPER_MODELMEET,//添加模板会议
	SYSTEMLOG_OPER_ADMINLOGONERR,//管理员登陆出错
	SYSTEMLOG_OPER_ADDDIR,//添加目录
	SYSTEMLOG_OPER_MODIFYDIR,//修改目录（param[0]=dirid）
	SYSTEMLOG_OPER_DELETEDIR,//删除目录（param[0]=dirid）
	SYSTEMLOG_OPER_CLOSEFILE,//退出文件查看器（param[0]=dirid）
	SYSTEMLOG_OPER_REBOOT,//设备重启
	SYSTEMLOG_OPER_POWEROFF,//设备关机
	SYSTEMLOG_OPER_LIFTUP,//设备上升
	SYSTEMLOG_OPER_LIFTDOWN,//设备下降
	SYSTEMLOG_OPER_LIFTSTOP,//设备停止
	SYSTEMLOG_OPER_SOFTREBOOT,//软件重启
	SYSTEMLOG_OPER_WAKUP,//设备唤醒
	SYSTEMLOG_OPER_NETTEST,//设备网络测试
	SYSTEMLOG_OPER_HELPSIGN,//辅助签到
	SYSTEMLOG_OPER_NOSIGNENTER,//免签
	SYSTEMLOG_OPER_OPENOUTSIDE,//外部打开文档
	SYSTEMLOG_OPER_PROTECTDATA,//资料保护
	SYSTEMLOG_OPER_MODIFYDEVICE,//修改设备信息
	SYSTEMLOG_OPER_DELDEVICE,//删除设备
	SYSTEMLOG_OPER_SETINI,//参数配置
	SYSTEMLOG_OPER_COMMONADD,//添加
	SYSTEMLOG_OPER_COMMONMODIFY,//修改
	SYSTEMLOG_OPER_COMMONDELETE,//删除
	SYSTEMLOG_OPER_COMMONSAVE,//保存
	SYSTEMLOG_OPER_COMMONIMPORT,//导入
	SYSTEMLOG_OPER_COMMONEXPORT,//导出
	SYSTEMLOG_OPER_COMMONSTART,//开始
	SYSTEMLOG_OPER_COMMONSTOP,//结束
	SYSTEMLOG_OPER_COMMONDETAIL,//查询详情
	SYSTEMLOG_OPER_SETHOST,//设置主持人
	SYSTEMLOG_OPER_COMMONADDGROUP,//添加分组
	SYSTEMLOG_OPER_COMMONMODIFYGROUP,//修改分组
	SYSTEMLOG_OPER_COMMONDELETEGROUP,//删除分组
	SYSTEMLOG_OPER_MEETARCHIVE,//会议归档
	SYSTEMLOG_OPER_ADDCONTROLROOM,//添加可控会场
	SYSTEMLOG_OPER_DELCONTROLROOM,//删除可控会场
	SYSTEMLOG_OPER_DELSYSLOG,//执行日志清理
	SYSTEMLOG_OPER_GUESTMODE,//访客模式
	SYSTEMLOG_OPER_RESETMEETDATA,//重置会议数据

};

#endif