[versions]
agp = "8.7.3"
kotlin = "1.9.24"
coreKtx = "1.10.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# https://github.com/greenrobot/EventBus
eventbus = { group = "org.greenrobot", name = "eventbus", version = "3.3.1" }
# 基础工具类大全：https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/README-CN.md
utilcodex = { group = "com.blankj", name = "utilcodex", version = "1.31.1" }
# 权限请求框架：https://github.com/getActivity/XXPermissions
xxPermissions = { group = "com.github.getActivity", name = "XXPermissions", version = "23.0" }
# https://gitee.com/xlk_gitee/paperless_sdk
paperlessSdk = { group = "com.gitee.xlk_gitee", name = "paperless_sdk", version = "1.0.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

