[versions]
agp = "8.7.3"
kotlin = "1.8.0"
coreKtx = "1.8.0"
appcompat = "1.4.1"
material = "1.5.0"
activity = "1.5.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
recyclerview = "1.3.0"
lifecycle = "2.5.1"
xxPermissions = "28.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
# 权限请求框架：https://github.com/getActivity/XXPermissions
xxPermissions = { group = "com.github.getActivity", name = "XXPermissions", version.ref = "xxPermissions" }

# https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-extensions
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }

# https://github.com/greenrobot/EventBus
eventbus = { group = "org.greenrobot", name = "eventbus", version = "3.3.1" }
# 基础工具类大全：https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/README-CN.md
utilcodex = { group = "com.blankj", name = "utilcodex", version = "1.31.1" }
# https://github.com/liangjingkanji/BRV
brv = { group = "com.github.liangjingkanji", name = "BRV", version = "1.6.1" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[bundles]
lifecycleLib = ["lifecycle-common", "lifecycle-livedata", "lifecycle-viewmodel"]
lifecycleKtxLib = ["lifecycle-extensions", "lifecycle-runtime-ktx", "lifecycle-livedata-ktx", "lifecycle-viewmodel-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

