// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_meetfunction.proto

package com.mogujie.tt.protobuf;

public final class InterfaceMeetfunction {
  private InterfaceMeetfunction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   *桌牌修改标志位
   * </pre>
   *
   * Protobuf enum {@code Pb_FunCon_ModifyFlag}
   */
  public enum Pb_FunCon_ModifyFlag
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Pb_FUNCONFIG_MODFLAG_ZERO = 0;</code>
     */
    Pb_FUNCONFIG_MODFLAG_ZERO(0),
    /**
     * <pre>
     *设置为默认
     * </pre>
     *
     * <code>Pb_FUNCONFIG_MODFLAG_SETDEFAULT = 1;</code>
     */
    Pb_FUNCONFIG_MODFLAG_SETDEFAULT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Pb_FUNCONFIG_MODFLAG_ZERO = 0;</code>
     */
    public static final int Pb_FUNCONFIG_MODFLAG_ZERO_VALUE = 0;
    /**
     * <pre>
     *设置为默认
     * </pre>
     *
     * <code>Pb_FUNCONFIG_MODFLAG_SETDEFAULT = 1;</code>
     */
    public static final int Pb_FUNCONFIG_MODFLAG_SETDEFAULT_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Pb_FunCon_ModifyFlag valueOf(int value) {
      return forNumber(value);
    }

    public static Pb_FunCon_ModifyFlag forNumber(int value) {
      switch (value) {
        case 0: return Pb_FUNCONFIG_MODFLAG_ZERO;
        case 1: return Pb_FUNCONFIG_MODFLAG_SETDEFAULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Pb_FunCon_ModifyFlag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Pb_FunCon_ModifyFlag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Pb_FunCon_ModifyFlag>() {
            public Pb_FunCon_ModifyFlag findValueByNumber(int number) {
              return Pb_FunCon_ModifyFlag.forNumber(number);
            }
          };

    private final int value;

    private Pb_FunCon_ModifyFlag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pb_FunCon_ModifyFlag)
  }

  public interface pbui_Item_MeetFunConfigDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_MeetFunConfigDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *功能标识码 参见Pb_Meet_FunctionCode
     * </pre>
     *
     * <code>optional fixed32 funcode = 1;</code>
     */
    int getFuncode();

    /**
     * <pre>
     *位置标识码
     * </pre>
     *
     * <code>optional fixed32 position = 2;</code>
     */
    int getPosition();
  }
  /**
   * <pre>
   *会议功能
   * </pre>
   *
   * Protobuf type {@code pbui_Item_MeetFunConfigDetailInfo}
   */
  public  static final class pbui_Item_MeetFunConfigDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_MeetFunConfigDetailInfo, pbui_Item_MeetFunConfigDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_MeetFunConfigDetailInfo)
      pbui_Item_MeetFunConfigDetailInfoOrBuilder {
    private pbui_Item_MeetFunConfigDetailInfo() {
    }
    public static final int FUNCODE_FIELD_NUMBER = 1;
    private int funcode_;
    /**
     * <pre>
     *功能标识码 参见Pb_Meet_FunctionCode
     * </pre>
     *
     * <code>optional fixed32 funcode = 1;</code>
     */
    public int getFuncode() {
      return funcode_;
    }
    /**
     * <pre>
     *功能标识码 参见Pb_Meet_FunctionCode
     * </pre>
     *
     * <code>optional fixed32 funcode = 1;</code>
     */
    private void setFuncode(int value) {
      
      funcode_ = value;
    }
    /**
     * <pre>
     *功能标识码 参见Pb_Meet_FunctionCode
     * </pre>
     *
     * <code>optional fixed32 funcode = 1;</code>
     */
    private void clearFuncode() {
      
      funcode_ = 0;
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private int position_;
    /**
     * <pre>
     *位置标识码
     * </pre>
     *
     * <code>optional fixed32 position = 2;</code>
     */
    public int getPosition() {
      return position_;
    }
    /**
     * <pre>
     *位置标识码
     * </pre>
     *
     * <code>optional fixed32 position = 2;</code>
     */
    private void setPosition(int value) {
      
      position_ = value;
    }
    /**
     * <pre>
     *位置标识码
     * </pre>
     *
     * <code>optional fixed32 position = 2;</code>
     */
    private void clearPosition() {
      
      position_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (funcode_ != 0) {
        output.writeFixed32(1, funcode_);
      }
      if (position_ != 0) {
        output.writeFixed32(2, position_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (funcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, funcode_);
      }
      if (position_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, position_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *会议功能
     * </pre>
     *
     * Protobuf type {@code pbui_Item_MeetFunConfigDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_MeetFunConfigDetailInfo)
        com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *功能标识码 参见Pb_Meet_FunctionCode
       * </pre>
       *
       * <code>optional fixed32 funcode = 1;</code>
       */
      public int getFuncode() {
        return instance.getFuncode();
      }
      /**
       * <pre>
       *功能标识码 参见Pb_Meet_FunctionCode
       * </pre>
       *
       * <code>optional fixed32 funcode = 1;</code>
       */
      public Builder setFuncode(int value) {
        copyOnWrite();
        instance.setFuncode(value);
        return this;
      }
      /**
       * <pre>
       *功能标识码 参见Pb_Meet_FunctionCode
       * </pre>
       *
       * <code>optional fixed32 funcode = 1;</code>
       */
      public Builder clearFuncode() {
        copyOnWrite();
        instance.clearFuncode();
        return this;
      }

      /**
       * <pre>
       *位置标识码
       * </pre>
       *
       * <code>optional fixed32 position = 2;</code>
       */
      public int getPosition() {
        return instance.getPosition();
      }
      /**
       * <pre>
       *位置标识码
       * </pre>
       *
       * <code>optional fixed32 position = 2;</code>
       */
      public Builder setPosition(int value) {
        copyOnWrite();
        instance.setPosition(value);
        return this;
      }
      /**
       * <pre>
       *位置标识码
       * </pre>
       *
       * <code>optional fixed32 position = 2;</code>
       */
      public Builder clearPosition() {
        copyOnWrite();
        instance.clearPosition();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_MeetFunConfigDetailInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo other = (com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo) arg1;
          funcode_ = visitor.visitInt(funcode_ != 0, funcode_,
              other.funcode_ != 0, other.funcode_);
          position_ = visitor.visitInt(position_ != 0, position_,
              other.position_ != 0, other.position_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  funcode_ = input.readFixed32();
                  break;
                }
                case 21: {

                  position_ = input.readFixed32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_MeetFunConfigDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_MeetFunConfigDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_MeetFunConfigDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_MeetFunConfigDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_MeetFunConfigDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_MeetFunConfigDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *修改标志 参见Pb_FunCon_ModifyFlag
     * </pre>
     *
     * <code>optional fixed32 modifyflag = 1;</code>
     */
    int getModifyflag();

    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo> 
        getItemList();
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo getItem(int index);
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    int getItemCount();

    /**
     * <pre>
     *指定会议ID
     * </pre>
     *
     * <code>optional fixed32 meetid = 3;</code>
     */
    int getMeetid();
  }
  /**
   * <pre>
   *会议功能
   *type:Pb_TYPE_MEET_INTERFACE_FUNCONFIG
   *method: query/save/
   * </pre>
   *
   * Protobuf type {@code pbui_Type_MeetFunConfigDetailInfo}
   */
  public  static final class pbui_Type_MeetFunConfigDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_MeetFunConfigDetailInfo, pbui_Type_MeetFunConfigDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_MeetFunConfigDetailInfo)
      pbui_Type_MeetFunConfigDetailInfoOrBuilder {
    private pbui_Type_MeetFunConfigDetailInfo() {
      item_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int MODIFYFLAG_FIELD_NUMBER = 1;
    private int modifyflag_;
    /**
     * <pre>
     *修改标志 参见Pb_FunCon_ModifyFlag
     * </pre>
     *
     * <code>optional fixed32 modifyflag = 1;</code>
     */
    public int getModifyflag() {
      return modifyflag_;
    }
    /**
     * <pre>
     *修改标志 参见Pb_FunCon_ModifyFlag
     * </pre>
     *
     * <code>optional fixed32 modifyflag = 1;</code>
     */
    private void setModifyflag(int value) {
      
      modifyflag_ = value;
    }
    /**
     * <pre>
     *修改标志 参见Pb_FunCon_ModifyFlag
     * </pre>
     *
     * <code>optional fixed32 modifyflag = 1;</code>
     */
    private void clearModifyflag() {
      
      modifyflag_ = 0;
    }

    public static final int ITEM_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo> item_;
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfoOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfoOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    private void ensureItemIsMutable() {
      if (!item_.isModifiable()) {
        item_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
       }
    }

    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void addItem(com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(value);
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void addItem(
        com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void addAllItem(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo> values) {
      ensureItemIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, item_);
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void clearItem() {
      item_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
     */
    private void removeItem(int index) {
      ensureItemIsMutable();
      item_.remove(index);
    }

    public static final int MEETID_FIELD_NUMBER = 3;
    private int meetid_;
    /**
     * <pre>
     *指定会议ID
     * </pre>
     *
     * <code>optional fixed32 meetid = 3;</code>
     */
    public int getMeetid() {
      return meetid_;
    }
    /**
     * <pre>
     *指定会议ID
     * </pre>
     *
     * <code>optional fixed32 meetid = 3;</code>
     */
    private void setMeetid(int value) {
      
      meetid_ = value;
    }
    /**
     * <pre>
     *指定会议ID
     * </pre>
     *
     * <code>optional fixed32 meetid = 3;</code>
     */
    private void clearMeetid() {
      
      meetid_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modifyflag_ != 0) {
        output.writeFixed32(1, modifyflag_);
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
      if (meetid_ != 0) {
        output.writeFixed32(3, meetid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (modifyflag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, modifyflag_);
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      if (meetid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, meetid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *会议功能
     *type:Pb_TYPE_MEET_INTERFACE_FUNCONFIG
     *method: query/save/
     * </pre>
     *
     * Protobuf type {@code pbui_Type_MeetFunConfigDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_MeetFunConfigDetailInfo)
        com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *修改标志 参见Pb_FunCon_ModifyFlag
       * </pre>
       *
       * <code>optional fixed32 modifyflag = 1;</code>
       */
      public int getModifyflag() {
        return instance.getModifyflag();
      }
      /**
       * <pre>
       *修改标志 参见Pb_FunCon_ModifyFlag
       * </pre>
       *
       * <code>optional fixed32 modifyflag = 1;</code>
       */
      public Builder setModifyflag(int value) {
        copyOnWrite();
        instance.setModifyflag(value);
        return this;
      }
      /**
       * <pre>
       *修改标志 参见Pb_FunCon_ModifyFlag
       * </pre>
       *
       * <code>optional fixed32 modifyflag = 1;</code>
       */
      public Builder clearModifyflag() {
        copyOnWrite();
        instance.clearModifyflag();
        return this;
      }

      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo> getItemList() {
        return java.util.Collections.unmodifiableList(
            instance.getItemList());
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }/**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo getItem(int index) {
        return instance.getItem(index);
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo value) {
        copyOnWrite();
        instance.setItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder addItem(com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo value) {
        copyOnWrite();
        instance.addItem(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo value) {
        copyOnWrite();
        instance.addItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder addItem(
          com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo> values) {
        copyOnWrite();
        instance.addAllItem(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder clearItem() {
        copyOnWrite();
        instance.clearItem();
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetFunConfigDetailInfo item = 2;</code>
       */
      public Builder removeItem(int index) {
        copyOnWrite();
        instance.removeItem(index);
        return this;
      }

      /**
       * <pre>
       *指定会议ID
       * </pre>
       *
       * <code>optional fixed32 meetid = 3;</code>
       */
      public int getMeetid() {
        return instance.getMeetid();
      }
      /**
       * <pre>
       *指定会议ID
       * </pre>
       *
       * <code>optional fixed32 meetid = 3;</code>
       */
      public Builder setMeetid(int value) {
        copyOnWrite();
        instance.setMeetid(value);
        return this;
      }
      /**
       * <pre>
       *指定会议ID
       * </pre>
       *
       * <code>optional fixed32 meetid = 3;</code>
       */
      public Builder clearMeetid() {
        copyOnWrite();
        instance.clearMeetid();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_MeetFunConfigDetailInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          item_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo other = (com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo) arg1;
          modifyflag_ = visitor.visitInt(modifyflag_ != 0, modifyflag_,
              other.modifyflag_ != 0, other.modifyflag_);
          item_= visitor.visitList(item_, other.item_);
          meetid_ = visitor.visitInt(meetid_ != 0, meetid_,
              other.meetid_ != 0, other.meetid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  modifyflag_ = input.readFixed32();
                  break;
                }
                case 18: {
                  if (!item_.isModifiable()) {
                    item_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
                  }
                  item_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Item_MeetFunConfigDetailInfo.parser(), extensionRegistry));
                  break;
                }
                case 29: {

                  meetid_ = input.readFixed32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_MeetFunConfigDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_MeetFunConfigDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetfunction.pbui_Type_MeetFunConfigDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_MeetFunConfigDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_MeetFunConfigDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
