// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_meetuserdef.proto

package com.mogujie.tt.protobuf;

public final class InterfaceMeetuserdef {
  private InterfaceMeetuserdef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   *会议自定义数据项ID
   * </pre>
   *
   * Protobuf enum {@code Pb_MeetUserDefFlag}
   */
  public enum Pb_MeetUserDefFlag
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Pb_MeetUserDef_ZERO = 0;</code>
     */
    Pb_MeetUserDef_ZERO(0),
    /**
     * <pre>
     *会议标语
     * </pre>
     *
     * <code>Pb_MeetUserDef_SLOGAN = 1;</code>
     */
    Pb_MeetUserDef_SLOGAN(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Pb_MeetUserDef_ZERO = 0;</code>
     */
    public static final int Pb_MeetUserDef_ZERO_VALUE = 0;
    /**
     * <pre>
     *会议标语
     * </pre>
     *
     * <code>Pb_MeetUserDef_SLOGAN = 1;</code>
     */
    public static final int Pb_MeetUserDef_SLOGAN_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Pb_MeetUserDefFlag valueOf(int value) {
      return forNumber(value);
    }

    public static Pb_MeetUserDefFlag forNumber(int value) {
      switch (value) {
        case 0: return Pb_MeetUserDef_ZERO;
        case 1: return Pb_MeetUserDef_SLOGAN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Pb_MeetUserDefFlag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Pb_MeetUserDefFlag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Pb_MeetUserDefFlag>() {
            public Pb_MeetUserDefFlag findValueByNumber(int number) {
              return Pb_MeetUserDefFlag.forNumber(number);
            }
          };

    private final int value;

    private Pb_MeetUserDefFlag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pb_MeetUserDefFlag)
  }

  public interface pbui_Type_MeetUserdefItemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_MeetUserdefItemInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *数据id 用户自行约定
     * </pre>
     *
     * <code>optional fixed32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes text = 2;</code>
     */
    com.google.protobuf.ByteString getText();
  }
  /**
   * Protobuf type {@code pbui_Type_MeetUserdefItemInfo}
   */
  public  static final class pbui_Type_MeetUserdefItemInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_MeetUserdefItemInfo, pbui_Type_MeetUserdefItemInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_MeetUserdefItemInfo)
      pbui_Type_MeetUserdefItemInfoOrBuilder {
    private pbui_Type_MeetUserdefItemInfo() {
      text_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *数据id 用户自行约定
     * </pre>
     *
     * <code>optional fixed32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     *数据id 用户自行约定
     * </pre>
     *
     * <code>optional fixed32 id = 1;</code>
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <pre>
     *数据id 用户自行约定
     * </pre>
     *
     * <code>optional fixed32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString text_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes text = 2;</code>
     */
    public com.google.protobuf.ByteString getText() {
      return text_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes text = 2;</code>
     */
    private void setText(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes text = 2;</code>
     */
    private void clearText() {
      
      text_ = getDefaultInstance().getText();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeFixed32(1, id_);
      }
      if (!text_.isEmpty()) {
        output.writeBytes(2, text_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, id_);
      }
      if (!text_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, text_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code pbui_Type_MeetUserdefItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_MeetUserdefItemInfo)
        com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *数据id 用户自行约定
       * </pre>
       *
       * <code>optional fixed32 id = 1;</code>
       */
      public int getId() {
        return instance.getId();
      }
      /**
       * <pre>
       *数据id 用户自行约定
       * </pre>
       *
       * <code>optional fixed32 id = 1;</code>
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       *数据id 用户自行约定
       * </pre>
       *
       * <code>optional fixed32 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes text = 2;</code>
       */
      public com.google.protobuf.ByteString getText() {
        return instance.getText();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes text = 2;</code>
       */
      public Builder setText(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setText(value);
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes text = 2;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_MeetUserdefItemInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo other = (com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo) arg1;
          id_ = visitor.visitInt(id_ != 0, id_,
              other.id_ != 0, other.id_);
          text_ = visitor.visitByteString(text_ != com.google.protobuf.ByteString.EMPTY, text_,
              other.text_ != com.google.protobuf.ByteString.EMPTY, other.text_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  id_ = input.readFixed32();
                  break;
                }
                case 18: {

                  text_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_MeetUserdefItemInfo)
    private static final com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_MeetUserdefItemInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_MeetUserdefItemInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_MeetUserdefItemInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_MeetUserdefInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_MeetUserdefInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *指定会议id 为0表示当前会议
     * </pre>
     *
     * <code>optional fixed32 meetid = 1;</code>
     */
    int getMeetid();

    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo> 
        getItemList();
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo getItem(int index);
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    int getItemCount();
  }
  /**
   * <pre>
   *call
   *type:TYPE_MEET_INTERFACE_MEETUSERDEF
   *method: 
   *METHOD_MEET_INTERFACE_SINGLEQUERYBYID|使用pbui_QueryInfoByID 
   *modify|delete|使用pbui_Type_MeetUserdefInfo
   * </pre>
   *
   * Protobuf type {@code pbui_Type_MeetUserdefInfo}
   */
  public  static final class pbui_Type_MeetUserdefInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_MeetUserdefInfo, pbui_Type_MeetUserdefInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_MeetUserdefInfo)
      pbui_Type_MeetUserdefInfoOrBuilder {
    private pbui_Type_MeetUserdefInfo() {
      item_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int MEETID_FIELD_NUMBER = 1;
    private int meetid_;
    /**
     * <pre>
     *指定会议id 为0表示当前会议
     * </pre>
     *
     * <code>optional fixed32 meetid = 1;</code>
     */
    public int getMeetid() {
      return meetid_;
    }
    /**
     * <pre>
     *指定会议id 为0表示当前会议
     * </pre>
     *
     * <code>optional fixed32 meetid = 1;</code>
     */
    private void setMeetid(int value) {
      
      meetid_ = value;
    }
    /**
     * <pre>
     *指定会议id 为0表示当前会议
     * </pre>
     *
     * <code>optional fixed32 meetid = 1;</code>
     */
    private void clearMeetid() {
      
      meetid_ = 0;
    }

    public static final int ITEM_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo> item_;
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfoOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfoOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    private void ensureItemIsMutable() {
      if (!item_.isModifiable()) {
        item_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
       }
    }

    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void addItem(com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(value);
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void addItem(
        com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void addAllItem(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo> values) {
      ensureItemIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, item_);
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void clearItem() {
      item_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
     */
    private void removeItem(int index) {
      ensureItemIsMutable();
      item_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (meetid_ != 0) {
        output.writeFixed32(1, meetid_);
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (meetid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, meetid_);
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *call
     *type:TYPE_MEET_INTERFACE_MEETUSERDEF
     *method: 
     *METHOD_MEET_INTERFACE_SINGLEQUERYBYID|使用pbui_QueryInfoByID 
     *modify|delete|使用pbui_Type_MeetUserdefInfo
     * </pre>
     *
     * Protobuf type {@code pbui_Type_MeetUserdefInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_MeetUserdefInfo)
        com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *指定会议id 为0表示当前会议
       * </pre>
       *
       * <code>optional fixed32 meetid = 1;</code>
       */
      public int getMeetid() {
        return instance.getMeetid();
      }
      /**
       * <pre>
       *指定会议id 为0表示当前会议
       * </pre>
       *
       * <code>optional fixed32 meetid = 1;</code>
       */
      public Builder setMeetid(int value) {
        copyOnWrite();
        instance.setMeetid(value);
        return this;
      }
      /**
       * <pre>
       *指定会议id 为0表示当前会议
       * </pre>
       *
       * <code>optional fixed32 meetid = 1;</code>
       */
      public Builder clearMeetid() {
        copyOnWrite();
        instance.clearMeetid();
        return this;
      }

      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo> getItemList() {
        return java.util.Collections.unmodifiableList(
            instance.getItemList());
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }/**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo getItem(int index) {
        return instance.getItem(index);
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo value) {
        copyOnWrite();
        instance.setItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder addItem(com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo value) {
        copyOnWrite();
        instance.addItem(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo value) {
        copyOnWrite();
        instance.addItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder addItem(
          com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo> values) {
        copyOnWrite();
        instance.addAllItem(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder clearItem() {
        copyOnWrite();
        instance.clearItem();
        return this;
      }
      /**
       * <code>repeated .pbui_Type_MeetUserdefItemInfo item = 2;</code>
       */
      public Builder removeItem(int index) {
        copyOnWrite();
        instance.removeItem(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_MeetUserdefInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          item_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo other = (com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo) arg1;
          meetid_ = visitor.visitInt(meetid_ != 0, meetid_,
              other.meetid_ != 0, other.meetid_);
          item_= visitor.visitList(item_, other.item_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  meetid_ = input.readFixed32();
                  break;
                }
                case 18: {
                  if (!item_.isModifiable()) {
                    item_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
                  }
                  item_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefItemInfo.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_MeetUserdefInfo)
    private static final com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_MeetUserdefInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceMeetuserdef.pbui_Type_MeetUserdefInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_MeetUserdefInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_MeetUserdefInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
