// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_faceconfig.proto

package com.mogujie.tt.protobuf;

public final class InterfaceFaceconfig {
  private InterfaceFaceconfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface pbui_Item_FaceTextItemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_FaceTextItemInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    int getFaceid();

    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    int getFlag();

    /**
     * <pre>
     *字体大小
     * </pre>
     *
     * <code>optional fixed32 fontsize = 3;</code>
     */
    int getFontsize();

    /**
     * <pre>
     *字体rgba颜色
     * </pre>
     *
     * <code>optional fixed32 color = 4;</code>
     */
    int getColor();

    /**
     * <pre>
     *对齐 参见 Pb_FontAlignFlag
     * </pre>
     *
     * <code>optional fixed32 align = 5;</code>
     */
    int getAlign();

    /**
     * <pre>
     *字体属性 Pb_MeetFaceFontFlag
     * </pre>
     *
     * <code>optional fixed32 fontflag = 6;</code>
     */
    int getFontflag();

    /**
     * <pre>
     *字体名称
     * </pre>
     *
     * <code>optional bytes fontname = 7;</code>
     */
    com.google.protobuf.ByteString getFontname();

    /**
     * <pre>
     *坐标 左上角x  (x * 100 / width)
     * </pre>
     *
     * <code>optional float lx = 8;</code>
     */
    float getLx();

    /**
     * <pre>
     *坐标 左上角y  (y * 100 / height)
     * </pre>
     *
     * <code>optional float ly = 9;</code>
     */
    float getLy();

    /**
     * <pre>
     *坐标 右下角x
     * </pre>
     *
     * <code>optional float bx = 10;</code>
     */
    float getBx();

    /**
     * <pre>
     *坐标 右下角y
     * </pre>
     *
     * <code>optional float by = 11;</code>
     */
    float getBy();
  }
  /**
   * <pre>
   *文本项
   * </pre>
   *
   * Protobuf type {@code pbui_Item_FaceTextItemInfo}
   */
  public  static final class pbui_Item_FaceTextItemInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_FaceTextItemInfo, pbui_Item_FaceTextItemInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_FaceTextItemInfo)
      pbui_Item_FaceTextItemInfoOrBuilder {
    private pbui_Item_FaceTextItemInfo() {
      fontname_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FACEID_FIELD_NUMBER = 1;
    private int faceid_;
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    public int getFaceid() {
      return faceid_;
    }
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    private void setFaceid(int value) {
      
      faceid_ = value;
    }
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    private void clearFaceid() {
      
      faceid_ = 0;
    }

    public static final int FLAG_FIELD_NUMBER = 2;
    private int flag_;
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    public int getFlag() {
      return flag_;
    }
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    private void setFlag(int value) {
      
      flag_ = value;
    }
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    private void clearFlag() {
      
      flag_ = 0;
    }

    public static final int FONTSIZE_FIELD_NUMBER = 3;
    private int fontsize_;
    /**
     * <pre>
     *字体大小
     * </pre>
     *
     * <code>optional fixed32 fontsize = 3;</code>
     */
    public int getFontsize() {
      return fontsize_;
    }
    /**
     * <pre>
     *字体大小
     * </pre>
     *
     * <code>optional fixed32 fontsize = 3;</code>
     */
    private void setFontsize(int value) {
      
      fontsize_ = value;
    }
    /**
     * <pre>
     *字体大小
     * </pre>
     *
     * <code>optional fixed32 fontsize = 3;</code>
     */
    private void clearFontsize() {
      
      fontsize_ = 0;
    }

    public static final int COLOR_FIELD_NUMBER = 4;
    private int color_;
    /**
     * <pre>
     *字体rgba颜色
     * </pre>
     *
     * <code>optional fixed32 color = 4;</code>
     */
    public int getColor() {
      return color_;
    }
    /**
     * <pre>
     *字体rgba颜色
     * </pre>
     *
     * <code>optional fixed32 color = 4;</code>
     */
    private void setColor(int value) {
      
      color_ = value;
    }
    /**
     * <pre>
     *字体rgba颜色
     * </pre>
     *
     * <code>optional fixed32 color = 4;</code>
     */
    private void clearColor() {
      
      color_ = 0;
    }

    public static final int ALIGN_FIELD_NUMBER = 5;
    private int align_;
    /**
     * <pre>
     *对齐 参见 Pb_FontAlignFlag
     * </pre>
     *
     * <code>optional fixed32 align = 5;</code>
     */
    public int getAlign() {
      return align_;
    }
    /**
     * <pre>
     *对齐 参见 Pb_FontAlignFlag
     * </pre>
     *
     * <code>optional fixed32 align = 5;</code>
     */
    private void setAlign(int value) {
      
      align_ = value;
    }
    /**
     * <pre>
     *对齐 参见 Pb_FontAlignFlag
     * </pre>
     *
     * <code>optional fixed32 align = 5;</code>
     */
    private void clearAlign() {
      
      align_ = 0;
    }

    public static final int FONTFLAG_FIELD_NUMBER = 6;
    private int fontflag_;
    /**
     * <pre>
     *字体属性 Pb_MeetFaceFontFlag
     * </pre>
     *
     * <code>optional fixed32 fontflag = 6;</code>
     */
    public int getFontflag() {
      return fontflag_;
    }
    /**
     * <pre>
     *字体属性 Pb_MeetFaceFontFlag
     * </pre>
     *
     * <code>optional fixed32 fontflag = 6;</code>
     */
    private void setFontflag(int value) {
      
      fontflag_ = value;
    }
    /**
     * <pre>
     *字体属性 Pb_MeetFaceFontFlag
     * </pre>
     *
     * <code>optional fixed32 fontflag = 6;</code>
     */
    private void clearFontflag() {
      
      fontflag_ = 0;
    }

    public static final int FONTNAME_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString fontname_;
    /**
     * <pre>
     *字体名称
     * </pre>
     *
     * <code>optional bytes fontname = 7;</code>
     */
    public com.google.protobuf.ByteString getFontname() {
      return fontname_;
    }
    /**
     * <pre>
     *字体名称
     * </pre>
     *
     * <code>optional bytes fontname = 7;</code>
     */
    private void setFontname(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fontname_ = value;
    }
    /**
     * <pre>
     *字体名称
     * </pre>
     *
     * <code>optional bytes fontname = 7;</code>
     */
    private void clearFontname() {
      
      fontname_ = getDefaultInstance().getFontname();
    }

    public static final int LX_FIELD_NUMBER = 8;
    private float lx_;
    /**
     * <pre>
     *坐标 左上角x  (x * 100 / width)
     * </pre>
     *
     * <code>optional float lx = 8;</code>
     */
    public float getLx() {
      return lx_;
    }
    /**
     * <pre>
     *坐标 左上角x  (x * 100 / width)
     * </pre>
     *
     * <code>optional float lx = 8;</code>
     */
    private void setLx(float value) {
      
      lx_ = value;
    }
    /**
     * <pre>
     *坐标 左上角x  (x * 100 / width)
     * </pre>
     *
     * <code>optional float lx = 8;</code>
     */
    private void clearLx() {
      
      lx_ = 0F;
    }

    public static final int LY_FIELD_NUMBER = 9;
    private float ly_;
    /**
     * <pre>
     *坐标 左上角y  (y * 100 / height)
     * </pre>
     *
     * <code>optional float ly = 9;</code>
     */
    public float getLy() {
      return ly_;
    }
    /**
     * <pre>
     *坐标 左上角y  (y * 100 / height)
     * </pre>
     *
     * <code>optional float ly = 9;</code>
     */
    private void setLy(float value) {
      
      ly_ = value;
    }
    /**
     * <pre>
     *坐标 左上角y  (y * 100 / height)
     * </pre>
     *
     * <code>optional float ly = 9;</code>
     */
    private void clearLy() {
      
      ly_ = 0F;
    }

    public static final int BX_FIELD_NUMBER = 10;
    private float bx_;
    /**
     * <pre>
     *坐标 右下角x
     * </pre>
     *
     * <code>optional float bx = 10;</code>
     */
    public float getBx() {
      return bx_;
    }
    /**
     * <pre>
     *坐标 右下角x
     * </pre>
     *
     * <code>optional float bx = 10;</code>
     */
    private void setBx(float value) {
      
      bx_ = value;
    }
    /**
     * <pre>
     *坐标 右下角x
     * </pre>
     *
     * <code>optional float bx = 10;</code>
     */
    private void clearBx() {
      
      bx_ = 0F;
    }

    public static final int BY_FIELD_NUMBER = 11;
    private float by_;
    /**
     * <pre>
     *坐标 右下角y
     * </pre>
     *
     * <code>optional float by = 11;</code>
     */
    public float getBy() {
      return by_;
    }
    /**
     * <pre>
     *坐标 右下角y
     * </pre>
     *
     * <code>optional float by = 11;</code>
     */
    private void setBy(float value) {
      
      by_ = value;
    }
    /**
     * <pre>
     *坐标 右下角y
     * </pre>
     *
     * <code>optional float by = 11;</code>
     */
    private void clearBy() {
      
      by_ = 0F;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (faceid_ != 0) {
        output.writeFixed32(1, faceid_);
      }
      if (flag_ != 0) {
        output.writeFixed32(2, flag_);
      }
      if (fontsize_ != 0) {
        output.writeFixed32(3, fontsize_);
      }
      if (color_ != 0) {
        output.writeFixed32(4, color_);
      }
      if (align_ != 0) {
        output.writeFixed32(5, align_);
      }
      if (fontflag_ != 0) {
        output.writeFixed32(6, fontflag_);
      }
      if (!fontname_.isEmpty()) {
        output.writeBytes(7, fontname_);
      }
      if (lx_ != 0F) {
        output.writeFloat(8, lx_);
      }
      if (ly_ != 0F) {
        output.writeFloat(9, ly_);
      }
      if (bx_ != 0F) {
        output.writeFloat(10, bx_);
      }
      if (by_ != 0F) {
        output.writeFloat(11, by_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (faceid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, faceid_);
      }
      if (flag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, flag_);
      }
      if (fontsize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, fontsize_);
      }
      if (color_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, color_);
      }
      if (align_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(5, align_);
      }
      if (fontflag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(6, fontflag_);
      }
      if (!fontname_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, fontname_);
      }
      if (lx_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, lx_);
      }
      if (ly_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, ly_);
      }
      if (bx_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, bx_);
      }
      if (by_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, by_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *文本项
     * </pre>
     *
     * Protobuf type {@code pbui_Item_FaceTextItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_FaceTextItemInfo)
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public int getFaceid() {
        return instance.getFaceid();
      }
      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public Builder setFaceid(int value) {
        copyOnWrite();
        instance.setFaceid(value);
        return this;
      }
      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public Builder clearFaceid() {
        copyOnWrite();
        instance.clearFaceid();
        return this;
      }

      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public int getFlag() {
        return instance.getFlag();
      }
      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public Builder setFlag(int value) {
        copyOnWrite();
        instance.setFlag(value);
        return this;
      }
      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public Builder clearFlag() {
        copyOnWrite();
        instance.clearFlag();
        return this;
      }

      /**
       * <pre>
       *字体大小
       * </pre>
       *
       * <code>optional fixed32 fontsize = 3;</code>
       */
      public int getFontsize() {
        return instance.getFontsize();
      }
      /**
       * <pre>
       *字体大小
       * </pre>
       *
       * <code>optional fixed32 fontsize = 3;</code>
       */
      public Builder setFontsize(int value) {
        copyOnWrite();
        instance.setFontsize(value);
        return this;
      }
      /**
       * <pre>
       *字体大小
       * </pre>
       *
       * <code>optional fixed32 fontsize = 3;</code>
       */
      public Builder clearFontsize() {
        copyOnWrite();
        instance.clearFontsize();
        return this;
      }

      /**
       * <pre>
       *字体rgba颜色
       * </pre>
       *
       * <code>optional fixed32 color = 4;</code>
       */
      public int getColor() {
        return instance.getColor();
      }
      /**
       * <pre>
       *字体rgba颜色
       * </pre>
       *
       * <code>optional fixed32 color = 4;</code>
       */
      public Builder setColor(int value) {
        copyOnWrite();
        instance.setColor(value);
        return this;
      }
      /**
       * <pre>
       *字体rgba颜色
       * </pre>
       *
       * <code>optional fixed32 color = 4;</code>
       */
      public Builder clearColor() {
        copyOnWrite();
        instance.clearColor();
        return this;
      }

      /**
       * <pre>
       *对齐 参见 Pb_FontAlignFlag
       * </pre>
       *
       * <code>optional fixed32 align = 5;</code>
       */
      public int getAlign() {
        return instance.getAlign();
      }
      /**
       * <pre>
       *对齐 参见 Pb_FontAlignFlag
       * </pre>
       *
       * <code>optional fixed32 align = 5;</code>
       */
      public Builder setAlign(int value) {
        copyOnWrite();
        instance.setAlign(value);
        return this;
      }
      /**
       * <pre>
       *对齐 参见 Pb_FontAlignFlag
       * </pre>
       *
       * <code>optional fixed32 align = 5;</code>
       */
      public Builder clearAlign() {
        copyOnWrite();
        instance.clearAlign();
        return this;
      }

      /**
       * <pre>
       *字体属性 Pb_MeetFaceFontFlag
       * </pre>
       *
       * <code>optional fixed32 fontflag = 6;</code>
       */
      public int getFontflag() {
        return instance.getFontflag();
      }
      /**
       * <pre>
       *字体属性 Pb_MeetFaceFontFlag
       * </pre>
       *
       * <code>optional fixed32 fontflag = 6;</code>
       */
      public Builder setFontflag(int value) {
        copyOnWrite();
        instance.setFontflag(value);
        return this;
      }
      /**
       * <pre>
       *字体属性 Pb_MeetFaceFontFlag
       * </pre>
       *
       * <code>optional fixed32 fontflag = 6;</code>
       */
      public Builder clearFontflag() {
        copyOnWrite();
        instance.clearFontflag();
        return this;
      }

      /**
       * <pre>
       *字体名称
       * </pre>
       *
       * <code>optional bytes fontname = 7;</code>
       */
      public com.google.protobuf.ByteString getFontname() {
        return instance.getFontname();
      }
      /**
       * <pre>
       *字体名称
       * </pre>
       *
       * <code>optional bytes fontname = 7;</code>
       */
      public Builder setFontname(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFontname(value);
        return this;
      }
      /**
       * <pre>
       *字体名称
       * </pre>
       *
       * <code>optional bytes fontname = 7;</code>
       */
      public Builder clearFontname() {
        copyOnWrite();
        instance.clearFontname();
        return this;
      }

      /**
       * <pre>
       *坐标 左上角x  (x * 100 / width)
       * </pre>
       *
       * <code>optional float lx = 8;</code>
       */
      public float getLx() {
        return instance.getLx();
      }
      /**
       * <pre>
       *坐标 左上角x  (x * 100 / width)
       * </pre>
       *
       * <code>optional float lx = 8;</code>
       */
      public Builder setLx(float value) {
        copyOnWrite();
        instance.setLx(value);
        return this;
      }
      /**
       * <pre>
       *坐标 左上角x  (x * 100 / width)
       * </pre>
       *
       * <code>optional float lx = 8;</code>
       */
      public Builder clearLx() {
        copyOnWrite();
        instance.clearLx();
        return this;
      }

      /**
       * <pre>
       *坐标 左上角y  (y * 100 / height)
       * </pre>
       *
       * <code>optional float ly = 9;</code>
       */
      public float getLy() {
        return instance.getLy();
      }
      /**
       * <pre>
       *坐标 左上角y  (y * 100 / height)
       * </pre>
       *
       * <code>optional float ly = 9;</code>
       */
      public Builder setLy(float value) {
        copyOnWrite();
        instance.setLy(value);
        return this;
      }
      /**
       * <pre>
       *坐标 左上角y  (y * 100 / height)
       * </pre>
       *
       * <code>optional float ly = 9;</code>
       */
      public Builder clearLy() {
        copyOnWrite();
        instance.clearLy();
        return this;
      }

      /**
       * <pre>
       *坐标 右下角x
       * </pre>
       *
       * <code>optional float bx = 10;</code>
       */
      public float getBx() {
        return instance.getBx();
      }
      /**
       * <pre>
       *坐标 右下角x
       * </pre>
       *
       * <code>optional float bx = 10;</code>
       */
      public Builder setBx(float value) {
        copyOnWrite();
        instance.setBx(value);
        return this;
      }
      /**
       * <pre>
       *坐标 右下角x
       * </pre>
       *
       * <code>optional float bx = 10;</code>
       */
      public Builder clearBx() {
        copyOnWrite();
        instance.clearBx();
        return this;
      }

      /**
       * <pre>
       *坐标 右下角y
       * </pre>
       *
       * <code>optional float by = 11;</code>
       */
      public float getBy() {
        return instance.getBy();
      }
      /**
       * <pre>
       *坐标 右下角y
       * </pre>
       *
       * <code>optional float by = 11;</code>
       */
      public Builder setBy(float value) {
        copyOnWrite();
        instance.setBy(value);
        return this;
      }
      /**
       * <pre>
       *坐标 右下角y
       * </pre>
       *
       * <code>optional float by = 11;</code>
       */
      public Builder clearBy() {
        copyOnWrite();
        instance.clearBy();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_FaceTextItemInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo other = (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo) arg1;
          faceid_ = visitor.visitInt(faceid_ != 0, faceid_,
              other.faceid_ != 0, other.faceid_);
          flag_ = visitor.visitInt(flag_ != 0, flag_,
              other.flag_ != 0, other.flag_);
          fontsize_ = visitor.visitInt(fontsize_ != 0, fontsize_,
              other.fontsize_ != 0, other.fontsize_);
          color_ = visitor.visitInt(color_ != 0, color_,
              other.color_ != 0, other.color_);
          align_ = visitor.visitInt(align_ != 0, align_,
              other.align_ != 0, other.align_);
          fontflag_ = visitor.visitInt(fontflag_ != 0, fontflag_,
              other.fontflag_ != 0, other.fontflag_);
          fontname_ = visitor.visitByteString(fontname_ != com.google.protobuf.ByteString.EMPTY, fontname_,
              other.fontname_ != com.google.protobuf.ByteString.EMPTY, other.fontname_);
          lx_ = visitor.visitFloat(lx_ != 0F, lx_,
              other.lx_ != 0F, other.lx_);
          ly_ = visitor.visitFloat(ly_ != 0F, ly_,
              other.ly_ != 0F, other.ly_);
          bx_ = visitor.visitFloat(bx_ != 0F, bx_,
              other.bx_ != 0F, other.bx_);
          by_ = visitor.visitFloat(by_ != 0F, by_,
              other.by_ != 0F, other.by_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  faceid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  flag_ = input.readFixed32();
                  break;
                }
                case 29: {

                  fontsize_ = input.readFixed32();
                  break;
                }
                case 37: {

                  color_ = input.readFixed32();
                  break;
                }
                case 45: {

                  align_ = input.readFixed32();
                  break;
                }
                case 53: {

                  fontflag_ = input.readFixed32();
                  break;
                }
                case 58: {

                  fontname_ = input.readBytes();
                  break;
                }
                case 69: {

                  lx_ = input.readFloat();
                  break;
                }
                case 77: {

                  ly_ = input.readFloat();
                  break;
                }
                case 85: {

                  bx_ = input.readFloat();
                  break;
                }
                case 93: {

                  by_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_FaceTextItemInfo)
    private static final com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_FaceTextItemInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_FaceTextItemInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_FaceTextItemInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Item_FacePictureItemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_FacePictureItemInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    int getFaceid();

    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    int getFlag();

    /**
     * <pre>
     *项值
     * </pre>
     *
     * <code>optional fixed32 mediaid = 3;</code>
     */
    int getMediaid();
  }
  /**
   * <pre>
   *图片项
   * </pre>
   *
   * Protobuf type {@code pbui_Item_FacePictureItemInfo}
   */
  public  static final class pbui_Item_FacePictureItemInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_FacePictureItemInfo, pbui_Item_FacePictureItemInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_FacePictureItemInfo)
      pbui_Item_FacePictureItemInfoOrBuilder {
    private pbui_Item_FacePictureItemInfo() {
    }
    public static final int FACEID_FIELD_NUMBER = 1;
    private int faceid_;
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    public int getFaceid() {
      return faceid_;
    }
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    private void setFaceid(int value) {
      
      faceid_ = value;
    }
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    private void clearFaceid() {
      
      faceid_ = 0;
    }

    public static final int FLAG_FIELD_NUMBER = 2;
    private int flag_;
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    public int getFlag() {
      return flag_;
    }
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    private void setFlag(int value) {
      
      flag_ = value;
    }
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    private void clearFlag() {
      
      flag_ = 0;
    }

    public static final int MEDIAID_FIELD_NUMBER = 3;
    private int mediaid_;
    /**
     * <pre>
     *项值
     * </pre>
     *
     * <code>optional fixed32 mediaid = 3;</code>
     */
    public int getMediaid() {
      return mediaid_;
    }
    /**
     * <pre>
     *项值
     * </pre>
     *
     * <code>optional fixed32 mediaid = 3;</code>
     */
    private void setMediaid(int value) {
      
      mediaid_ = value;
    }
    /**
     * <pre>
     *项值
     * </pre>
     *
     * <code>optional fixed32 mediaid = 3;</code>
     */
    private void clearMediaid() {
      
      mediaid_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (faceid_ != 0) {
        output.writeFixed32(1, faceid_);
      }
      if (flag_ != 0) {
        output.writeFixed32(2, flag_);
      }
      if (mediaid_ != 0) {
        output.writeFixed32(3, mediaid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (faceid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, faceid_);
      }
      if (flag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, flag_);
      }
      if (mediaid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, mediaid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *图片项
     * </pre>
     *
     * Protobuf type {@code pbui_Item_FacePictureItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_FacePictureItemInfo)
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public int getFaceid() {
        return instance.getFaceid();
      }
      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public Builder setFaceid(int value) {
        copyOnWrite();
        instance.setFaceid(value);
        return this;
      }
      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public Builder clearFaceid() {
        copyOnWrite();
        instance.clearFaceid();
        return this;
      }

      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public int getFlag() {
        return instance.getFlag();
      }
      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public Builder setFlag(int value) {
        copyOnWrite();
        instance.setFlag(value);
        return this;
      }
      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public Builder clearFlag() {
        copyOnWrite();
        instance.clearFlag();
        return this;
      }

      /**
       * <pre>
       *项值
       * </pre>
       *
       * <code>optional fixed32 mediaid = 3;</code>
       */
      public int getMediaid() {
        return instance.getMediaid();
      }
      /**
       * <pre>
       *项值
       * </pre>
       *
       * <code>optional fixed32 mediaid = 3;</code>
       */
      public Builder setMediaid(int value) {
        copyOnWrite();
        instance.setMediaid(value);
        return this;
      }
      /**
       * <pre>
       *项值
       * </pre>
       *
       * <code>optional fixed32 mediaid = 3;</code>
       */
      public Builder clearMediaid() {
        copyOnWrite();
        instance.clearMediaid();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_FacePictureItemInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo other = (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo) arg1;
          faceid_ = visitor.visitInt(faceid_ != 0, faceid_,
              other.faceid_ != 0, other.faceid_);
          flag_ = visitor.visitInt(flag_ != 0, flag_,
              other.flag_ != 0, other.flag_);
          mediaid_ = visitor.visitInt(mediaid_ != 0, mediaid_,
              other.mediaid_ != 0, other.mediaid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  faceid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  flag_ = input.readFixed32();
                  break;
                }
                case 29: {

                  mediaid_ = input.readFixed32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_FacePictureItemInfo)
    private static final com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_FacePictureItemInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_FacePictureItemInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_FacePictureItemInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Item_FaceOnlyTextItemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_FaceOnlyTextItemInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    int getFaceid();

    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    int getFlag();

    /**
     * <pre>
     *文本
     * </pre>
     *
     * <code>optional bytes text = 3;</code>
     */
    com.google.protobuf.ByteString getText();
  }
  /**
   * <pre>
   *纯文本项
   * </pre>
   *
   * Protobuf type {@code pbui_Item_FaceOnlyTextItemInfo}
   */
  public  static final class pbui_Item_FaceOnlyTextItemInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_FaceOnlyTextItemInfo, pbui_Item_FaceOnlyTextItemInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_FaceOnlyTextItemInfo)
      pbui_Item_FaceOnlyTextItemInfoOrBuilder {
    private pbui_Item_FaceOnlyTextItemInfo() {
      text_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FACEID_FIELD_NUMBER = 1;
    private int faceid_;
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    public int getFaceid() {
      return faceid_;
    }
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    private void setFaceid(int value) {
      
      faceid_ = value;
    }
    /**
     * <pre>
     *界面项ID 参见Pb_MeetFaceID
     * </pre>
     *
     * <code>optional fixed32 faceid = 1;</code>
     */
    private void clearFaceid() {
      
      faceid_ = 0;
    }

    public static final int FLAG_FIELD_NUMBER = 2;
    private int flag_;
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    public int getFlag() {
      return flag_;
    }
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    private void setFlag(int value) {
      
      flag_ = value;
    }
    /**
     * <pre>
     *属性值 参见Pb_MeetFaceFlag
     * </pre>
     *
     * <code>optional fixed32 flag = 2;</code>
     */
    private void clearFlag() {
      
      flag_ = 0;
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString text_;
    /**
     * <pre>
     *文本
     * </pre>
     *
     * <code>optional bytes text = 3;</code>
     */
    public com.google.protobuf.ByteString getText() {
      return text_;
    }
    /**
     * <pre>
     *文本
     * </pre>
     *
     * <code>optional bytes text = 3;</code>
     */
    private void setText(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
    }
    /**
     * <pre>
     *文本
     * </pre>
     *
     * <code>optional bytes text = 3;</code>
     */
    private void clearText() {
      
      text_ = getDefaultInstance().getText();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (faceid_ != 0) {
        output.writeFixed32(1, faceid_);
      }
      if (flag_ != 0) {
        output.writeFixed32(2, flag_);
      }
      if (!text_.isEmpty()) {
        output.writeBytes(3, text_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (faceid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, faceid_);
      }
      if (flag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, flag_);
      }
      if (!text_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, text_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *纯文本项
     * </pre>
     *
     * Protobuf type {@code pbui_Item_FaceOnlyTextItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_FaceOnlyTextItemInfo)
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public int getFaceid() {
        return instance.getFaceid();
      }
      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public Builder setFaceid(int value) {
        copyOnWrite();
        instance.setFaceid(value);
        return this;
      }
      /**
       * <pre>
       *界面项ID 参见Pb_MeetFaceID
       * </pre>
       *
       * <code>optional fixed32 faceid = 1;</code>
       */
      public Builder clearFaceid() {
        copyOnWrite();
        instance.clearFaceid();
        return this;
      }

      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public int getFlag() {
        return instance.getFlag();
      }
      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public Builder setFlag(int value) {
        copyOnWrite();
        instance.setFlag(value);
        return this;
      }
      /**
       * <pre>
       *属性值 参见Pb_MeetFaceFlag
       * </pre>
       *
       * <code>optional fixed32 flag = 2;</code>
       */
      public Builder clearFlag() {
        copyOnWrite();
        instance.clearFlag();
        return this;
      }

      /**
       * <pre>
       *文本
       * </pre>
       *
       * <code>optional bytes text = 3;</code>
       */
      public com.google.protobuf.ByteString getText() {
        return instance.getText();
      }
      /**
       * <pre>
       *文本
       * </pre>
       *
       * <code>optional bytes text = 3;</code>
       */
      public Builder setText(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setText(value);
        return this;
      }
      /**
       * <pre>
       *文本
       * </pre>
       *
       * <code>optional bytes text = 3;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_FaceOnlyTextItemInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo other = (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo) arg1;
          faceid_ = visitor.visitInt(faceid_ != 0, faceid_,
              other.faceid_ != 0, other.faceid_);
          flag_ = visitor.visitInt(flag_ != 0, flag_,
              other.flag_ != 0, other.flag_);
          text_ = visitor.visitByteString(text_ != com.google.protobuf.ByteString.EMPTY, text_,
              other.text_ != com.google.protobuf.ByteString.EMPTY, other.text_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  faceid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  flag_ = input.readFixed32();
                  break;
                }
                case 26: {

                  text_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_FaceOnlyTextItemInfo)
    private static final com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_FaceOnlyTextItemInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_FaceOnlyTextItemInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_FaceOnlyTextItemInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_FaceConfigInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_FaceConfigInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo> 
        getTextList();
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo getText(int index);
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    int getTextCount();

    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo> 
        getPictureList();
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo getPicture(int index);
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    int getPictureCount();

    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo> 
        getOnlytextList();
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo getOnlytext(int index);
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    int getOnlytextCount();
  }
  /**
   * <pre>
   *callreturn
   *type:Pb_TYPE_MEET_INTERFACE_MEETFACECONFIG
   *method: siglequerybyid query modify
   * </pre>
   *
   * Protobuf type {@code pbui_Type_FaceConfigInfo}
   */
  public  static final class pbui_Type_FaceConfigInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_FaceConfigInfo, pbui_Type_FaceConfigInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_FaceConfigInfo)
      pbui_Type_FaceConfigInfoOrBuilder {
    private pbui_Type_FaceConfigInfo() {
      text_ = emptyProtobufList();
      picture_ = emptyProtobufList();
      onlytext_ = emptyProtobufList();
    }
    public static final int TEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo> text_;
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo> getTextList() {
      return text_;
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfoOrBuilder> 
        getTextOrBuilderList() {
      return text_;
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfoOrBuilder getTextOrBuilder(
        int index) {
      return text_.get(index);
    }
    private void ensureTextIsMutable() {
      if (!text_.isModifiable()) {
        text_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(text_);
       }
    }

    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void setText(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTextIsMutable();
      text_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void setText(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.Builder builderForValue) {
      ensureTextIsMutable();
      text_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void addText(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTextIsMutable();
      text_.add(value);
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void addText(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTextIsMutable();
      text_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void addText(
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.Builder builderForValue) {
      ensureTextIsMutable();
      text_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void addText(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.Builder builderForValue) {
      ensureTextIsMutable();
      text_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void addAllText(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo> values) {
      ensureTextIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, text_);
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void clearText() {
      text_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
     */
    private void removeText(int index) {
      ensureTextIsMutable();
      text_.remove(index);
    }

    public static final int PICTURE_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo> picture_;
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo> getPictureList() {
      return picture_;
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfoOrBuilder> 
        getPictureOrBuilderList() {
      return picture_;
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    public int getPictureCount() {
      return picture_.size();
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo getPicture(int index) {
      return picture_.get(index);
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfoOrBuilder getPictureOrBuilder(
        int index) {
      return picture_.get(index);
    }
    private void ensurePictureIsMutable() {
      if (!picture_.isModifiable()) {
        picture_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(picture_);
       }
    }

    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void setPicture(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePictureIsMutable();
      picture_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void setPicture(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.Builder builderForValue) {
      ensurePictureIsMutable();
      picture_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void addPicture(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePictureIsMutable();
      picture_.add(value);
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void addPicture(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePictureIsMutable();
      picture_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void addPicture(
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.Builder builderForValue) {
      ensurePictureIsMutable();
      picture_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void addPicture(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.Builder builderForValue) {
      ensurePictureIsMutable();
      picture_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void addAllPicture(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo> values) {
      ensurePictureIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, picture_);
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void clearPicture() {
      picture_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
     */
    private void removePicture(int index) {
      ensurePictureIsMutable();
      picture_.remove(index);
    }

    public static final int ONLYTEXT_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo> onlytext_;
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo> getOnlytextList() {
      return onlytext_;
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfoOrBuilder> 
        getOnlytextOrBuilderList() {
      return onlytext_;
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    public int getOnlytextCount() {
      return onlytext_.size();
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo getOnlytext(int index) {
      return onlytext_.get(index);
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfoOrBuilder getOnlytextOrBuilder(
        int index) {
      return onlytext_.get(index);
    }
    private void ensureOnlytextIsMutable() {
      if (!onlytext_.isModifiable()) {
        onlytext_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(onlytext_);
       }
    }

    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void setOnlytext(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOnlytextIsMutable();
      onlytext_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void setOnlytext(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.Builder builderForValue) {
      ensureOnlytextIsMutable();
      onlytext_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void addOnlytext(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOnlytextIsMutable();
      onlytext_.add(value);
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void addOnlytext(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOnlytextIsMutable();
      onlytext_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void addOnlytext(
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.Builder builderForValue) {
      ensureOnlytextIsMutable();
      onlytext_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void addOnlytext(
        int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.Builder builderForValue) {
      ensureOnlytextIsMutable();
      onlytext_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void addAllOnlytext(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo> values) {
      ensureOnlytextIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, onlytext_);
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void clearOnlytext() {
      onlytext_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
     */
    private void removeOnlytext(int index) {
      ensureOnlytextIsMutable();
      onlytext_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < text_.size(); i++) {
        output.writeMessage(1, text_.get(i));
      }
      for (int i = 0; i < picture_.size(); i++) {
        output.writeMessage(2, picture_.get(i));
      }
      for (int i = 0; i < onlytext_.size(); i++) {
        output.writeMessage(3, onlytext_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < text_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, text_.get(i));
      }
      for (int i = 0; i < picture_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, picture_.get(i));
      }
      for (int i = 0; i < onlytext_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, onlytext_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *callreturn
     *type:Pb_TYPE_MEET_INTERFACE_MEETFACECONFIG
     *method: siglequerybyid query modify
     * </pre>
     *
     * Protobuf type {@code pbui_Type_FaceConfigInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_FaceConfigInfo)
        com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo> getTextList() {
        return java.util.Collections.unmodifiableList(
            instance.getTextList());
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public int getTextCount() {
        return instance.getTextCount();
      }/**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo getText(int index) {
        return instance.getText(index);
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder setText(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo value) {
        copyOnWrite();
        instance.setText(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder setText(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setText(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder addText(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo value) {
        copyOnWrite();
        instance.addText(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder addText(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo value) {
        copyOnWrite();
        instance.addText(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder addText(
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addText(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder addText(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addText(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder addAllText(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo> values) {
        copyOnWrite();
        instance.addAllText(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceTextItemInfo text = 1;</code>
       */
      public Builder removeText(int index) {
        copyOnWrite();
        instance.removeText(index);
        return this;
      }

      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo> getPictureList() {
        return java.util.Collections.unmodifiableList(
            instance.getPictureList());
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public int getPictureCount() {
        return instance.getPictureCount();
      }/**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo getPicture(int index) {
        return instance.getPicture(index);
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder setPicture(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo value) {
        copyOnWrite();
        instance.setPicture(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder setPicture(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setPicture(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder addPicture(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo value) {
        copyOnWrite();
        instance.addPicture(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder addPicture(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo value) {
        copyOnWrite();
        instance.addPicture(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder addPicture(
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addPicture(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder addPicture(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addPicture(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder addAllPicture(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo> values) {
        copyOnWrite();
        instance.addAllPicture(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder clearPicture() {
        copyOnWrite();
        instance.clearPicture();
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FacePictureItemInfo picture = 2;</code>
       */
      public Builder removePicture(int index) {
        copyOnWrite();
        instance.removePicture(index);
        return this;
      }

      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo> getOnlytextList() {
        return java.util.Collections.unmodifiableList(
            instance.getOnlytextList());
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public int getOnlytextCount() {
        return instance.getOnlytextCount();
      }/**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo getOnlytext(int index) {
        return instance.getOnlytext(index);
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder setOnlytext(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo value) {
        copyOnWrite();
        instance.setOnlytext(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder setOnlytext(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setOnlytext(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder addOnlytext(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo value) {
        copyOnWrite();
        instance.addOnlytext(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder addOnlytext(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo value) {
        copyOnWrite();
        instance.addOnlytext(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder addOnlytext(
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addOnlytext(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder addOnlytext(
          int index, com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addOnlytext(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder addAllOnlytext(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo> values) {
        copyOnWrite();
        instance.addAllOnlytext(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder clearOnlytext() {
        copyOnWrite();
        instance.clearOnlytext();
        return this;
      }
      /**
       * <code>repeated .pbui_Item_FaceOnlyTextItemInfo onlytext = 3;</code>
       */
      public Builder removeOnlytext(int index) {
        copyOnWrite();
        instance.removeOnlytext(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_FaceConfigInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          text_.makeImmutable();
          picture_.makeImmutable();
          onlytext_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo other = (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo) arg1;
          text_= visitor.visitList(text_, other.text_);
          picture_= visitor.visitList(picture_, other.picture_);
          onlytext_= visitor.visitList(onlytext_, other.onlytext_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!text_.isModifiable()) {
                    text_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(text_);
                  }
                  text_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceTextItemInfo.parser(), extensionRegistry));
                  break;
                }
                case 18: {
                  if (!picture_.isModifiable()) {
                    picture_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(picture_);
                  }
                  picture_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FacePictureItemInfo.parser(), extensionRegistry));
                  break;
                }
                case 26: {
                  if (!onlytext_.isModifiable()) {
                    onlytext_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(onlytext_);
                  }
                  onlytext_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Item_FaceOnlyTextItemInfo.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_FaceConfigInfo)
    private static final com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_FaceConfigInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceFaceconfig.pbui_Type_FaceConfigInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_FaceConfigInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_FaceConfigInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
