// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_download.proto

package com.mogujie.tt.protobuf;

public final class InterfaceDownload {
  private InterfaceDownload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface pbui_Type_DownloadStartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_DownloadStart)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    int getMediaid();

    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 2;</code>
     */
    int getNewfile();

    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 3;</code>
     */
    int getOnlyfinish();

    /**
     * <pre>
     *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes pathname = 4;</code>
     */
    com.google.protobuf.ByteString getPathname();

    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    com.google.protobuf.ByteString getUserstr();

    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    com.google.protobuf.ByteString getPasswd();
  }
  /**
   * <pre>
   *执行下载
   *call
   *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
   *method: add
   * </pre>
   *
   * Protobuf type {@code pbui_Type_DownloadStart}
   */
  public  static final class pbui_Type_DownloadStart extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_DownloadStart, pbui_Type_DownloadStart.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_DownloadStart)
      pbui_Type_DownloadStartOrBuilder {
    private pbui_Type_DownloadStart() {
      pathname_ = com.google.protobuf.ByteString.EMPTY;
      userstr_ = com.google.protobuf.ByteString.EMPTY;
      passwd_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int MEDIAID_FIELD_NUMBER = 1;
    private int mediaid_;
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    public int getMediaid() {
      return mediaid_;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    private void setMediaid(int value) {
      
      mediaid_ = value;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    private void clearMediaid() {
      
      mediaid_ = 0;
    }

    public static final int NEWFILE_FIELD_NUMBER = 2;
    private int newfile_;
    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 2;</code>
     */
    public int getNewfile() {
      return newfile_;
    }
    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 2;</code>
     */
    private void setNewfile(int value) {
      
      newfile_ = value;
    }
    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 2;</code>
     */
    private void clearNewfile() {
      
      newfile_ = 0;
    }

    public static final int ONLYFINISH_FIELD_NUMBER = 3;
    private int onlyfinish_;
    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 3;</code>
     */
    public int getOnlyfinish() {
      return onlyfinish_;
    }
    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 3;</code>
     */
    private void setOnlyfinish(int value) {
      
      onlyfinish_ = value;
    }
    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 3;</code>
     */
    private void clearOnlyfinish() {
      
      onlyfinish_ = 0;
    }

    public static final int PATHNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString pathname_;
    /**
     * <pre>
     *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes pathname = 4;</code>
     */
    public com.google.protobuf.ByteString getPathname() {
      return pathname_;
    }
    /**
     * <pre>
     *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes pathname = 4;</code>
     */
    private void setPathname(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pathname_ = value;
    }
    /**
     * <pre>
     *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes pathname = 4;</code>
     */
    private void clearPathname() {
      
      pathname_ = getDefaultInstance().getPathname();
    }

    public static final int USERSTR_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString userstr_;
    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    public com.google.protobuf.ByteString getUserstr() {
      return userstr_;
    }
    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    private void setUserstr(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userstr_ = value;
    }
    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    private void clearUserstr() {
      
      userstr_ = getDefaultInstance().getUserstr();
    }

    public static final int PASSWD_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString passwd_;
    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    public com.google.protobuf.ByteString getPasswd() {
      return passwd_;
    }
    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    private void setPasswd(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passwd_ = value;
    }
    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    private void clearPasswd() {
      
      passwd_ = getDefaultInstance().getPasswd();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mediaid_ != 0) {
        output.writeFixed32(1, mediaid_);
      }
      if (newfile_ != 0) {
        output.writeFixed32(2, newfile_);
      }
      if (onlyfinish_ != 0) {
        output.writeFixed32(3, onlyfinish_);
      }
      if (!pathname_.isEmpty()) {
        output.writeBytes(4, pathname_);
      }
      if (!userstr_.isEmpty()) {
        output.writeBytes(5, userstr_);
      }
      if (!passwd_.isEmpty()) {
        output.writeBytes(6, passwd_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (mediaid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, mediaid_);
      }
      if (newfile_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, newfile_);
      }
      if (onlyfinish_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, onlyfinish_);
      }
      if (!pathname_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, pathname_);
      }
      if (!userstr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, userstr_);
      }
      if (!passwd_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, passwd_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *执行下载
     *call
     *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
     *method: add
     * </pre>
     *
     * Protobuf type {@code pbui_Type_DownloadStart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_DownloadStart)
        com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStartOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 1;</code>
       */
      public int getMediaid() {
        return instance.getMediaid();
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 1;</code>
       */
      public Builder setMediaid(int value) {
        copyOnWrite();
        instance.setMediaid(value);
        return this;
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 1;</code>
       */
      public Builder clearMediaid() {
        copyOnWrite();
        instance.clearMediaid();
        return this;
      }

      /**
       * <pre>
       *设置是否重新下载,0 不覆盖同名文件,重新下载
       * </pre>
       *
       * <code>optional fixed32 newfile = 2;</code>
       */
      public int getNewfile() {
        return instance.getNewfile();
      }
      /**
       * <pre>
       *设置是否重新下载,0 不覆盖同名文件,重新下载
       * </pre>
       *
       * <code>optional fixed32 newfile = 2;</code>
       */
      public Builder setNewfile(int value) {
        copyOnWrite();
        instance.setNewfile(value);
        return this;
      }
      /**
       * <pre>
       *设置是否重新下载,0 不覆盖同名文件,重新下载
       * </pre>
       *
       * <code>optional fixed32 newfile = 2;</code>
       */
      public Builder clearNewfile() {
        copyOnWrite();
        instance.clearNewfile();
        return this;
      }

      /**
       * <pre>
       *1表示只需要结束的通知
       * </pre>
       *
       * <code>optional fixed32 onlyfinish = 3;</code>
       */
      public int getOnlyfinish() {
        return instance.getOnlyfinish();
      }
      /**
       * <pre>
       *1表示只需要结束的通知
       * </pre>
       *
       * <code>optional fixed32 onlyfinish = 3;</code>
       */
      public Builder setOnlyfinish(int value) {
        copyOnWrite();
        instance.setOnlyfinish(value);
        return this;
      }
      /**
       * <pre>
       *1表示只需要结束的通知
       * </pre>
       *
       * <code>optional fixed32 onlyfinish = 3;</code>
       */
      public Builder clearOnlyfinish() {
        copyOnWrite();
        instance.clearOnlyfinish();
        return this;
      }

      /**
       * <pre>
       *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes pathname = 4;</code>
       */
      public com.google.protobuf.ByteString getPathname() {
        return instance.getPathname();
      }
      /**
       * <pre>
       *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes pathname = 4;</code>
       */
      public Builder setPathname(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPathname(value);
        return this;
      }
      /**
       * <pre>
       *下载媒体全路径名称 (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes pathname = 4;</code>
       */
      public Builder clearPathname() {
        copyOnWrite();
        instance.clearPathname();
        return this;
      }

      /**
       * <pre>
       *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 5;</code>
       */
      public com.google.protobuf.ByteString getUserstr() {
        return instance.getUserstr();
      }
      /**
       * <pre>
       *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 5;</code>
       */
      public Builder setUserstr(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserstr(value);
        return this;
      }
      /**
       * <pre>
       *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 5;</code>
       */
      public Builder clearUserstr() {
        copyOnWrite();
        instance.clearUserstr();
        return this;
      }

      /**
       * <pre>
       *文档加密密码, 为空表示无密码 密码最大长度为6
       * </pre>
       *
       * <code>optional bytes passwd = 6;</code>
       */
      public com.google.protobuf.ByteString getPasswd() {
        return instance.getPasswd();
      }
      /**
       * <pre>
       *文档加密密码, 为空表示无密码 密码最大长度为6
       * </pre>
       *
       * <code>optional bytes passwd = 6;</code>
       */
      public Builder setPasswd(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswd(value);
        return this;
      }
      /**
       * <pre>
       *文档加密密码, 为空表示无密码 密码最大长度为6
       * </pre>
       *
       * <code>optional bytes passwd = 6;</code>
       */
      public Builder clearPasswd() {
        copyOnWrite();
        instance.clearPasswd();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_DownloadStart)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart other = (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart) arg1;
          mediaid_ = visitor.visitInt(mediaid_ != 0, mediaid_,
              other.mediaid_ != 0, other.mediaid_);
          newfile_ = visitor.visitInt(newfile_ != 0, newfile_,
              other.newfile_ != 0, other.newfile_);
          onlyfinish_ = visitor.visitInt(onlyfinish_ != 0, onlyfinish_,
              other.onlyfinish_ != 0, other.onlyfinish_);
          pathname_ = visitor.visitByteString(pathname_ != com.google.protobuf.ByteString.EMPTY, pathname_,
              other.pathname_ != com.google.protobuf.ByteString.EMPTY, other.pathname_);
          userstr_ = visitor.visitByteString(userstr_ != com.google.protobuf.ByteString.EMPTY, userstr_,
              other.userstr_ != com.google.protobuf.ByteString.EMPTY, other.userstr_);
          passwd_ = visitor.visitByteString(passwd_ != com.google.protobuf.ByteString.EMPTY, passwd_,
              other.passwd_ != com.google.protobuf.ByteString.EMPTY, other.passwd_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  mediaid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  newfile_ = input.readFixed32();
                  break;
                }
                case 29: {

                  onlyfinish_ = input.readFixed32();
                  break;
                }
                case 34: {

                  pathname_ = input.readBytes();
                  break;
                }
                case 42: {

                  userstr_ = input.readBytes();
                  break;
                }
                case 50: {

                  passwd_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_DownloadStart)
    private static final com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_DownloadStart();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadStart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_DownloadStart> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_DownloadStart> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_DownloadCacheOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_DownloadCache)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *下载目录id
     * </pre>
     *
     * <code>optional fixed32 dirid = 1;</code>
     */
    int getDirid();

    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 2;</code>
     */
    int getMediaid();

    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 3;</code>
     */
    int getNewfile();

    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 4;</code>
     */
    int getOnlyfinish();

    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    com.google.protobuf.ByteString getUserstr();

    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    com.google.protobuf.ByteString getPasswd();
  }
  /**
   * <pre>
   *执行离线本地缓存 注:需要会议、会议室、会议目录、会议目录文件都准备好才会成功执行
   *call
   *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
   *method: cache
   * </pre>
   *
   * Protobuf type {@code pbui_Type_DownloadCache}
   */
  public  static final class pbui_Type_DownloadCache extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_DownloadCache, pbui_Type_DownloadCache.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_DownloadCache)
      pbui_Type_DownloadCacheOrBuilder {
    private pbui_Type_DownloadCache() {
      userstr_ = com.google.protobuf.ByteString.EMPTY;
      passwd_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int DIRID_FIELD_NUMBER = 1;
    private int dirid_;
    /**
     * <pre>
     *下载目录id
     * </pre>
     *
     * <code>optional fixed32 dirid = 1;</code>
     */
    public int getDirid() {
      return dirid_;
    }
    /**
     * <pre>
     *下载目录id
     * </pre>
     *
     * <code>optional fixed32 dirid = 1;</code>
     */
    private void setDirid(int value) {
      
      dirid_ = value;
    }
    /**
     * <pre>
     *下载目录id
     * </pre>
     *
     * <code>optional fixed32 dirid = 1;</code>
     */
    private void clearDirid() {
      
      dirid_ = 0;
    }

    public static final int MEDIAID_FIELD_NUMBER = 2;
    private int mediaid_;
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 2;</code>
     */
    public int getMediaid() {
      return mediaid_;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 2;</code>
     */
    private void setMediaid(int value) {
      
      mediaid_ = value;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 2;</code>
     */
    private void clearMediaid() {
      
      mediaid_ = 0;
    }

    public static final int NEWFILE_FIELD_NUMBER = 3;
    private int newfile_;
    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 3;</code>
     */
    public int getNewfile() {
      return newfile_;
    }
    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 3;</code>
     */
    private void setNewfile(int value) {
      
      newfile_ = value;
    }
    /**
     * <pre>
     *设置是否重新下载,0 不覆盖同名文件,重新下载
     * </pre>
     *
     * <code>optional fixed32 newfile = 3;</code>
     */
    private void clearNewfile() {
      
      newfile_ = 0;
    }

    public static final int ONLYFINISH_FIELD_NUMBER = 4;
    private int onlyfinish_;
    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 4;</code>
     */
    public int getOnlyfinish() {
      return onlyfinish_;
    }
    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 4;</code>
     */
    private void setOnlyfinish(int value) {
      
      onlyfinish_ = value;
    }
    /**
     * <pre>
     *1表示只需要结束的通知
     * </pre>
     *
     * <code>optional fixed32 onlyfinish = 4;</code>
     */
    private void clearOnlyfinish() {
      
      onlyfinish_ = 0;
    }

    public static final int USERSTR_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString userstr_;
    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    public com.google.protobuf.ByteString getUserstr() {
      return userstr_;
    }
    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    private void setUserstr(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userstr_ = value;
    }
    /**
     * <pre>
     *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 5;</code>
     */
    private void clearUserstr() {
      
      userstr_ = getDefaultInstance().getUserstr();
    }

    public static final int PASSWD_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString passwd_;
    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    public com.google.protobuf.ByteString getPasswd() {
      return passwd_;
    }
    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    private void setPasswd(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passwd_ = value;
    }
    /**
     * <pre>
     *文档加密密码, 为空表示无密码 密码最大长度为6
     * </pre>
     *
     * <code>optional bytes passwd = 6;</code>
     */
    private void clearPasswd() {
      
      passwd_ = getDefaultInstance().getPasswd();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dirid_ != 0) {
        output.writeFixed32(1, dirid_);
      }
      if (mediaid_ != 0) {
        output.writeFixed32(2, mediaid_);
      }
      if (newfile_ != 0) {
        output.writeFixed32(3, newfile_);
      }
      if (onlyfinish_ != 0) {
        output.writeFixed32(4, onlyfinish_);
      }
      if (!userstr_.isEmpty()) {
        output.writeBytes(5, userstr_);
      }
      if (!passwd_.isEmpty()) {
        output.writeBytes(6, passwd_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (dirid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, dirid_);
      }
      if (mediaid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, mediaid_);
      }
      if (newfile_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, newfile_);
      }
      if (onlyfinish_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, onlyfinish_);
      }
      if (!userstr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, userstr_);
      }
      if (!passwd_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, passwd_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *执行离线本地缓存 注:需要会议、会议室、会议目录、会议目录文件都准备好才会成功执行
     *call
     *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
     *method: cache
     * </pre>
     *
     * Protobuf type {@code pbui_Type_DownloadCache}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_DownloadCache)
        com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCacheOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *下载目录id
       * </pre>
       *
       * <code>optional fixed32 dirid = 1;</code>
       */
      public int getDirid() {
        return instance.getDirid();
      }
      /**
       * <pre>
       *下载目录id
       * </pre>
       *
       * <code>optional fixed32 dirid = 1;</code>
       */
      public Builder setDirid(int value) {
        copyOnWrite();
        instance.setDirid(value);
        return this;
      }
      /**
       * <pre>
       *下载目录id
       * </pre>
       *
       * <code>optional fixed32 dirid = 1;</code>
       */
      public Builder clearDirid() {
        copyOnWrite();
        instance.clearDirid();
        return this;
      }

      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 2;</code>
       */
      public int getMediaid() {
        return instance.getMediaid();
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 2;</code>
       */
      public Builder setMediaid(int value) {
        copyOnWrite();
        instance.setMediaid(value);
        return this;
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 2;</code>
       */
      public Builder clearMediaid() {
        copyOnWrite();
        instance.clearMediaid();
        return this;
      }

      /**
       * <pre>
       *设置是否重新下载,0 不覆盖同名文件,重新下载
       * </pre>
       *
       * <code>optional fixed32 newfile = 3;</code>
       */
      public int getNewfile() {
        return instance.getNewfile();
      }
      /**
       * <pre>
       *设置是否重新下载,0 不覆盖同名文件,重新下载
       * </pre>
       *
       * <code>optional fixed32 newfile = 3;</code>
       */
      public Builder setNewfile(int value) {
        copyOnWrite();
        instance.setNewfile(value);
        return this;
      }
      /**
       * <pre>
       *设置是否重新下载,0 不覆盖同名文件,重新下载
       * </pre>
       *
       * <code>optional fixed32 newfile = 3;</code>
       */
      public Builder clearNewfile() {
        copyOnWrite();
        instance.clearNewfile();
        return this;
      }

      /**
       * <pre>
       *1表示只需要结束的通知
       * </pre>
       *
       * <code>optional fixed32 onlyfinish = 4;</code>
       */
      public int getOnlyfinish() {
        return instance.getOnlyfinish();
      }
      /**
       * <pre>
       *1表示只需要结束的通知
       * </pre>
       *
       * <code>optional fixed32 onlyfinish = 4;</code>
       */
      public Builder setOnlyfinish(int value) {
        copyOnWrite();
        instance.setOnlyfinish(value);
        return this;
      }
      /**
       * <pre>
       *1表示只需要结束的通知
       * </pre>
       *
       * <code>optional fixed32 onlyfinish = 4;</code>
       */
      public Builder clearOnlyfinish() {
        copyOnWrite();
        instance.clearOnlyfinish();
        return this;
      }

      /**
       * <pre>
       *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 5;</code>
       */
      public com.google.protobuf.ByteString getUserstr() {
        return instance.getUserstr();
      }
      /**
       * <pre>
       *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 5;</code>
       */
      public Builder setUserstr(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserstr(value);
        return this;
      }
      /**
       * <pre>
       *用户传入的自定义字串(长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 5;</code>
       */
      public Builder clearUserstr() {
        copyOnWrite();
        instance.clearUserstr();
        return this;
      }

      /**
       * <pre>
       *文档加密密码, 为空表示无密码 密码最大长度为6
       * </pre>
       *
       * <code>optional bytes passwd = 6;</code>
       */
      public com.google.protobuf.ByteString getPasswd() {
        return instance.getPasswd();
      }
      /**
       * <pre>
       *文档加密密码, 为空表示无密码 密码最大长度为6
       * </pre>
       *
       * <code>optional bytes passwd = 6;</code>
       */
      public Builder setPasswd(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswd(value);
        return this;
      }
      /**
       * <pre>
       *文档加密密码, 为空表示无密码 密码最大长度为6
       * </pre>
       *
       * <code>optional bytes passwd = 6;</code>
       */
      public Builder clearPasswd() {
        copyOnWrite();
        instance.clearPasswd();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_DownloadCache)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache other = (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache) arg1;
          dirid_ = visitor.visitInt(dirid_ != 0, dirid_,
              other.dirid_ != 0, other.dirid_);
          mediaid_ = visitor.visitInt(mediaid_ != 0, mediaid_,
              other.mediaid_ != 0, other.mediaid_);
          newfile_ = visitor.visitInt(newfile_ != 0, newfile_,
              other.newfile_ != 0, other.newfile_);
          onlyfinish_ = visitor.visitInt(onlyfinish_ != 0, onlyfinish_,
              other.onlyfinish_ != 0, other.onlyfinish_);
          userstr_ = visitor.visitByteString(userstr_ != com.google.protobuf.ByteString.EMPTY, userstr_,
              other.userstr_ != com.google.protobuf.ByteString.EMPTY, other.userstr_);
          passwd_ = visitor.visitByteString(passwd_ != com.google.protobuf.ByteString.EMPTY, passwd_,
              other.passwd_ != com.google.protobuf.ByteString.EMPTY, other.passwd_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  dirid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  mediaid_ = input.readFixed32();
                  break;
                }
                case 29: {

                  newfile_ = input.readFixed32();
                  break;
                }
                case 37: {

                  onlyfinish_ = input.readFixed32();
                  break;
                }
                case 42: {

                  userstr_ = input.readBytes();
                  break;
                }
                case 50: {

                  passwd_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_DownloadCache)
    private static final com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_DownloadCache();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCache getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_DownloadCache> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_DownloadCache> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_DownloadDelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_DownloadDel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    int getMediaid();
  }
  /**
   * <pre>
   *删除一个下载
   *call
   *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
   *method: del
   * </pre>
   *
   * Protobuf type {@code pbui_Type_DownloadDel}
   */
  public  static final class pbui_Type_DownloadDel extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_DownloadDel, pbui_Type_DownloadDel.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_DownloadDel)
      pbui_Type_DownloadDelOrBuilder {
    private pbui_Type_DownloadDel() {
    }
    public static final int MEDIAID_FIELD_NUMBER = 1;
    private int mediaid_;
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    public int getMediaid() {
      return mediaid_;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    private void setMediaid(int value) {
      
      mediaid_ = value;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 1;</code>
     */
    private void clearMediaid() {
      
      mediaid_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mediaid_ != 0) {
        output.writeFixed32(1, mediaid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (mediaid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, mediaid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *删除一个下载
     *call
     *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
     *method: del
     * </pre>
     *
     * Protobuf type {@code pbui_Type_DownloadDel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_DownloadDel)
        com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDelOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 1;</code>
       */
      public int getMediaid() {
        return instance.getMediaid();
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 1;</code>
       */
      public Builder setMediaid(int value) {
        copyOnWrite();
        instance.setMediaid(value);
        return this;
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 1;</code>
       */
      public Builder clearMediaid() {
        copyOnWrite();
        instance.clearMediaid();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_DownloadDel)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel other = (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel) arg1;
          mediaid_ = visitor.visitInt(mediaid_ != 0, mediaid_,
              other.mediaid_ != 0, other.mediaid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  mediaid_ = input.readFixed32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_DownloadDel)
    private static final com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_DownloadDel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadDel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_DownloadDel> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_DownloadDel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_DownloadCbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_DownloadCb)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *下载进度
     * </pre>
     *
     * <code>optional fixed32 progress = 1;</code>
     */
    int getProgress();

    /**
     * <pre>
     *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
     * </pre>
     *
     * <code>optional fixed32 nstate = 2;</code>
     */
    int getNstate();

    /**
     * <pre>
     *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
     * </pre>
     *
     * <code>optional fixed32 err = 3;</code>
     */
    int getErr();

    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 4;</code>
     */
    int getMediaid();

    /**
     * <pre>
     *下载媒体全路径名称 (windows:mbcs linux:utf8)
     * </pre>
     *
     * <code>optional bytes pathname = 5;</code>
     */
    com.google.protobuf.ByteString getPathname();

    /**
     * <pre>
     *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 6;</code>
     */
    com.google.protobuf.ByteString getUserstr();
  }
  /**
   * <pre>
   *下载进度通知
   *callback
   *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
   *method: notify
   * </pre>
   *
   * Protobuf type {@code pbui_Type_DownloadCb}
   */
  public  static final class pbui_Type_DownloadCb extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_DownloadCb, pbui_Type_DownloadCb.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_DownloadCb)
      pbui_Type_DownloadCbOrBuilder {
    private pbui_Type_DownloadCb() {
      pathname_ = com.google.protobuf.ByteString.EMPTY;
      userstr_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int PROGRESS_FIELD_NUMBER = 1;
    private int progress_;
    /**
     * <pre>
     *下载进度
     * </pre>
     *
     * <code>optional fixed32 progress = 1;</code>
     */
    public int getProgress() {
      return progress_;
    }
    /**
     * <pre>
     *下载进度
     * </pre>
     *
     * <code>optional fixed32 progress = 1;</code>
     */
    private void setProgress(int value) {
      
      progress_ = value;
    }
    /**
     * <pre>
     *下载进度
     * </pre>
     *
     * <code>optional fixed32 progress = 1;</code>
     */
    private void clearProgress() {
      
      progress_ = 0;
    }

    public static final int NSTATE_FIELD_NUMBER = 2;
    private int nstate_;
    /**
     * <pre>
     *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
     * </pre>
     *
     * <code>optional fixed32 nstate = 2;</code>
     */
    public int getNstate() {
      return nstate_;
    }
    /**
     * <pre>
     *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
     * </pre>
     *
     * <code>optional fixed32 nstate = 2;</code>
     */
    private void setNstate(int value) {
      
      nstate_ = value;
    }
    /**
     * <pre>
     *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
     * </pre>
     *
     * <code>optional fixed32 nstate = 2;</code>
     */
    private void clearNstate() {
      
      nstate_ = 0;
    }

    public static final int ERR_FIELD_NUMBER = 3;
    private int err_;
    /**
     * <pre>
     *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
     * </pre>
     *
     * <code>optional fixed32 err = 3;</code>
     */
    public int getErr() {
      return err_;
    }
    /**
     * <pre>
     *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
     * </pre>
     *
     * <code>optional fixed32 err = 3;</code>
     */
    private void setErr(int value) {
      
      err_ = value;
    }
    /**
     * <pre>
     *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
     * </pre>
     *
     * <code>optional fixed32 err = 3;</code>
     */
    private void clearErr() {
      
      err_ = 0;
    }

    public static final int MEDIAID_FIELD_NUMBER = 4;
    private int mediaid_;
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 4;</code>
     */
    public int getMediaid() {
      return mediaid_;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 4;</code>
     */
    private void setMediaid(int value) {
      
      mediaid_ = value;
    }
    /**
     * <pre>
     *下载媒体id
     * </pre>
     *
     * <code>optional fixed32 mediaid = 4;</code>
     */
    private void clearMediaid() {
      
      mediaid_ = 0;
    }

    public static final int PATHNAME_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString pathname_;
    /**
     * <pre>
     *下载媒体全路径名称 (windows:mbcs linux:utf8)
     * </pre>
     *
     * <code>optional bytes pathname = 5;</code>
     */
    public com.google.protobuf.ByteString getPathname() {
      return pathname_;
    }
    /**
     * <pre>
     *下载媒体全路径名称 (windows:mbcs linux:utf8)
     * </pre>
     *
     * <code>optional bytes pathname = 5;</code>
     */
    private void setPathname(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pathname_ = value;
    }
    /**
     * <pre>
     *下载媒体全路径名称 (windows:mbcs linux:utf8)
     * </pre>
     *
     * <code>optional bytes pathname = 5;</code>
     */
    private void clearPathname() {
      
      pathname_ = getDefaultInstance().getPathname();
    }

    public static final int USERSTR_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString userstr_;
    /**
     * <pre>
     *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 6;</code>
     */
    public com.google.protobuf.ByteString getUserstr() {
      return userstr_;
    }
    /**
     * <pre>
     *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 6;</code>
     */
    private void setUserstr(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userstr_ = value;
    }
    /**
     * <pre>
     *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
     * </pre>
     *
     * <code>optional bytes userstr = 6;</code>
     */
    private void clearUserstr() {
      
      userstr_ = getDefaultInstance().getUserstr();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (progress_ != 0) {
        output.writeFixed32(1, progress_);
      }
      if (nstate_ != 0) {
        output.writeFixed32(2, nstate_);
      }
      if (err_ != 0) {
        output.writeFixed32(3, err_);
      }
      if (mediaid_ != 0) {
        output.writeFixed32(4, mediaid_);
      }
      if (!pathname_.isEmpty()) {
        output.writeBytes(5, pathname_);
      }
      if (!userstr_.isEmpty()) {
        output.writeBytes(6, userstr_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (progress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, progress_);
      }
      if (nstate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, nstate_);
      }
      if (err_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, err_);
      }
      if (mediaid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, mediaid_);
      }
      if (!pathname_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, pathname_);
      }
      if (!userstr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, userstr_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *下载进度通知
     *callback
     *type:Pb_TYPE_MEET_INTERFACE_DOWNLOAD
     *method: notify
     * </pre>
     *
     * Protobuf type {@code pbui_Type_DownloadCb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_DownloadCb)
        com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCbOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *下载进度
       * </pre>
       *
       * <code>optional fixed32 progress = 1;</code>
       */
      public int getProgress() {
        return instance.getProgress();
      }
      /**
       * <pre>
       *下载进度
       * </pre>
       *
       * <code>optional fixed32 progress = 1;</code>
       */
      public Builder setProgress(int value) {
        copyOnWrite();
        instance.setProgress(value);
        return this;
      }
      /**
       * <pre>
       *下载进度
       * </pre>
       *
       * <code>optional fixed32 progress = 1;</code>
       */
      public Builder clearProgress() {
        copyOnWrite();
        instance.clearProgress();
        return this;
      }

      /**
       * <pre>
       *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
       * </pre>
       *
       * <code>optional fixed32 nstate = 2;</code>
       */
      public int getNstate() {
        return instance.getNstate();
      }
      /**
       * <pre>
       *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
       * </pre>
       *
       * <code>optional fixed32 nstate = 2;</code>
       */
      public Builder setNstate(int value) {
        copyOnWrite();
        instance.setNstate(value);
        return this;
      }
      /**
       * <pre>
       *下载状态,参见Interface_Macro.proto ---&gt;Pb_Download_State
       * </pre>
       *
       * <code>optional fixed32 nstate = 2;</code>
       */
      public Builder clearNstate() {
        copyOnWrite();
        instance.clearNstate();
        return this;
      }

      /**
       * <pre>
       *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
       * </pre>
       *
       * <code>optional fixed32 err = 3;</code>
       */
      public int getErr() {
        return instance.getErr();
      }
      /**
       * <pre>
       *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
       * </pre>
       *
       * <code>optional fixed32 err = 3;</code>
       */
      public Builder setErr(int value) {
        copyOnWrite();
        instance.setErr(value);
        return this;
      }
      /**
       * <pre>
       *错误值 参见Interface_Macro.proto ---&gt;Pb_Download_Erro
       * </pre>
       *
       * <code>optional fixed32 err = 3;</code>
       */
      public Builder clearErr() {
        copyOnWrite();
        instance.clearErr();
        return this;
      }

      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 4;</code>
       */
      public int getMediaid() {
        return instance.getMediaid();
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 4;</code>
       */
      public Builder setMediaid(int value) {
        copyOnWrite();
        instance.setMediaid(value);
        return this;
      }
      /**
       * <pre>
       *下载媒体id
       * </pre>
       *
       * <code>optional fixed32 mediaid = 4;</code>
       */
      public Builder clearMediaid() {
        copyOnWrite();
        instance.clearMediaid();
        return this;
      }

      /**
       * <pre>
       *下载媒体全路径名称 (windows:mbcs linux:utf8)
       * </pre>
       *
       * <code>optional bytes pathname = 5;</code>
       */
      public com.google.protobuf.ByteString getPathname() {
        return instance.getPathname();
      }
      /**
       * <pre>
       *下载媒体全路径名称 (windows:mbcs linux:utf8)
       * </pre>
       *
       * <code>optional bytes pathname = 5;</code>
       */
      public Builder setPathname(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPathname(value);
        return this;
      }
      /**
       * <pre>
       *下载媒体全路径名称 (windows:mbcs linux:utf8)
       * </pre>
       *
       * <code>optional bytes pathname = 5;</code>
       */
      public Builder clearPathname() {
        copyOnWrite();
        instance.clearPathname();
        return this;
      }

      /**
       * <pre>
       *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 6;</code>
       */
      public com.google.protobuf.ByteString getUserstr() {
        return instance.getUserstr();
      }
      /**
       * <pre>
       *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 6;</code>
       */
      public Builder setUserstr(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserstr(value);
        return this;
      }
      /**
       * <pre>
       *用户传入的自定义字串(原编码格式返回) (长度不能超过 Pb_DEFAULT_DESCRIBE_LENG 定义的长度)
       * </pre>
       *
       * <code>optional bytes userstr = 6;</code>
       */
      public Builder clearUserstr() {
        copyOnWrite();
        instance.clearUserstr();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_DownloadCb)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb other = (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb) arg1;
          progress_ = visitor.visitInt(progress_ != 0, progress_,
              other.progress_ != 0, other.progress_);
          nstate_ = visitor.visitInt(nstate_ != 0, nstate_,
              other.nstate_ != 0, other.nstate_);
          err_ = visitor.visitInt(err_ != 0, err_,
              other.err_ != 0, other.err_);
          mediaid_ = visitor.visitInt(mediaid_ != 0, mediaid_,
              other.mediaid_ != 0, other.mediaid_);
          pathname_ = visitor.visitByteString(pathname_ != com.google.protobuf.ByteString.EMPTY, pathname_,
              other.pathname_ != com.google.protobuf.ByteString.EMPTY, other.pathname_);
          userstr_ = visitor.visitByteString(userstr_ != com.google.protobuf.ByteString.EMPTY, userstr_,
              other.userstr_ != com.google.protobuf.ByteString.EMPTY, other.userstr_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  progress_ = input.readFixed32();
                  break;
                }
                case 21: {

                  nstate_ = input.readFixed32();
                  break;
                }
                case 29: {

                  err_ = input.readFixed32();
                  break;
                }
                case 37: {

                  mediaid_ = input.readFixed32();
                  break;
                }
                case 42: {

                  pathname_ = input.readBytes();
                  break;
                }
                case 50: {

                  userstr_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_DownloadCb)
    private static final com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_DownloadCb();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceDownload.pbui_Type_DownloadCb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_DownloadCb> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_DownloadCb> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
