// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_publicinfo.proto

package com.mogujie.tt.protobuf;

public final class InterfacePublicinfo {
  private InterfacePublicinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   *会议自定义数据项ID
   * </pre>
   *
   * Protobuf enum {@code Pb_PublicDefFlag}
   */
  public enum Pb_PublicDefFlag
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Pb_MEET_PUBLIINFO_ZERO = 0;</code>
     */
    Pb_MEET_PUBLIINFO_ZERO(0),
    /**
     * <code>Pb_MEET_PUBLIINFO_SYSTEMUSE = 1;</code>
     */
    Pb_MEET_PUBLIINFO_SYSTEMUSE(1),
    /**
     * <pre>
     *MAXHUB白板系统的服务器地址 {"scanServerIp":"10.248.6.208","scanServerPort":"8889","serverIp":"10.248.6.11","serverPort":"61000"}
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_MAXHUBSERVERURL = 2;</code>
     */
    Pb_MEET_PUBLIINFO_MAXHUBSERVERURL(2),
    /**
     * <pre>
     *会议资料缓存 {"enable":"1","size":"150"} enable:是否启用 size:超过指定大小的 单位:M
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_DATACACHE = 3;</code>
     */
    Pb_MEET_PUBLIINFO_DATACACHE(3),
    /**
     * <pre>
     *会议定期清理 {"enable":"1","day":"7"} enable:是否启用 day:清理指定天数前的 单位:天
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_MEETRECYCLE = 4;</code>
     */
    Pb_MEET_PUBLIINFO_MEETRECYCLE(4),
    /**
     * <pre>
     *office绑定的pdf文件 {"arr":[{"a":"0xb0000001","b":"0xb0000002"}]} a=office文件id,b=pdf文件Id V2协议才支持
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_OFFICEBINDPDF = 5;</code>
     */
    Pb_MEET_PUBLIINFO_OFFICEBINDPDF(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Pb_MEET_PUBLIINFO_ZERO = 0;</code>
     */
    public static final int Pb_MEET_PUBLIINFO_ZERO_VALUE = 0;
    /**
     * <code>Pb_MEET_PUBLIINFO_SYSTEMUSE = 1;</code>
     */
    public static final int Pb_MEET_PUBLIINFO_SYSTEMUSE_VALUE = 1;
    /**
     * <pre>
     *MAXHUB白板系统的服务器地址 {"scanServerIp":"10.248.6.208","scanServerPort":"8889","serverIp":"10.248.6.11","serverPort":"61000"}
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_MAXHUBSERVERURL = 2;</code>
     */
    public static final int Pb_MEET_PUBLIINFO_MAXHUBSERVERURL_VALUE = 2;
    /**
     * <pre>
     *会议资料缓存 {"enable":"1","size":"150"} enable:是否启用 size:超过指定大小的 单位:M
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_DATACACHE = 3;</code>
     */
    public static final int Pb_MEET_PUBLIINFO_DATACACHE_VALUE = 3;
    /**
     * <pre>
     *会议定期清理 {"enable":"1","day":"7"} enable:是否启用 day:清理指定天数前的 单位:天
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_MEETRECYCLE = 4;</code>
     */
    public static final int Pb_MEET_PUBLIINFO_MEETRECYCLE_VALUE = 4;
    /**
     * <pre>
     *office绑定的pdf文件 {"arr":[{"a":"0xb0000001","b":"0xb0000002"}]} a=office文件id,b=pdf文件Id V2协议才支持
     * </pre>
     *
     * <code>Pb_MEET_PUBLIINFO_OFFICEBINDPDF = 5;</code>
     */
    public static final int Pb_MEET_PUBLIINFO_OFFICEBINDPDF_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Pb_PublicDefFlag valueOf(int value) {
      return forNumber(value);
    }

    public static Pb_PublicDefFlag forNumber(int value) {
      switch (value) {
        case 0: return Pb_MEET_PUBLIINFO_ZERO;
        case 1: return Pb_MEET_PUBLIINFO_SYSTEMUSE;
        case 2: return Pb_MEET_PUBLIINFO_MAXHUBSERVERURL;
        case 3: return Pb_MEET_PUBLIINFO_DATACACHE;
        case 4: return Pb_MEET_PUBLIINFO_MEETRECYCLE;
        case 5: return Pb_MEET_PUBLIINFO_OFFICEBINDPDF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Pb_PublicDefFlag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Pb_PublicDefFlag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Pb_PublicDefFlag>() {
            public Pb_PublicDefFlag findValueByNumber(int number) {
              return Pb_PublicDefFlag.forNumber(number);
            }
          };

    private final int value;

    private Pb_PublicDefFlag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pb_PublicDefFlag)
  }

  /**
   * <pre>
   *查询指定系统全局字串的某项属性
   *property id
   * </pre>
   *
   * Protobuf enum {@code Pb_PublicPropertyId}
   */
  public enum Pb_PublicPropertyId
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Pb_PUBLICINFO_PROPERT_ZERO = 0;</code>
     */
    Pb_PUBLICINFO_PROPERT_ZERO(0),
    /**
     * <pre>
     *查询Office文档绑定的Pdfid parameterval=officemediaid 返回intval
     * </pre>
     *
     * <code>Pb_PUBLICINFO_PROPERTY_OFFICEBINDID = 1;</code>
     */
    Pb_PUBLICINFO_PROPERTY_OFFICEBINDID(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Pb_PUBLICINFO_PROPERT_ZERO = 0;</code>
     */
    public static final int Pb_PUBLICINFO_PROPERT_ZERO_VALUE = 0;
    /**
     * <pre>
     *查询Office文档绑定的Pdfid parameterval=officemediaid 返回intval
     * </pre>
     *
     * <code>Pb_PUBLICINFO_PROPERTY_OFFICEBINDID = 1;</code>
     */
    public static final int Pb_PUBLICINFO_PROPERTY_OFFICEBINDID_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Pb_PublicPropertyId valueOf(int value) {
      return forNumber(value);
    }

    public static Pb_PublicPropertyId forNumber(int value) {
      switch (value) {
        case 0: return Pb_PUBLICINFO_PROPERT_ZERO;
        case 1: return Pb_PUBLICINFO_PROPERTY_OFFICEBINDID;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Pb_PublicPropertyId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Pb_PublicPropertyId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Pb_PublicPropertyId>() {
            public Pb_PublicPropertyId findValueByNumber(int number) {
              return Pb_PublicPropertyId.forNumber(number);
            }
          };

    private final int value;

    private Pb_PublicPropertyId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pb_PublicPropertyId)
  }

  public interface pbui_Type_meetQueryPublicInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_meetQueryPublicInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    java.util.List<java.lang.Integer> getDataidList();
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    int getDataidCount();
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    int getDataid(int index);
  }
  /**
   * <pre>
   *查询系统全局字串
   *call
   *TYPE_MEET_INTERFACE_PUBLICINFO
   *method:notify/query(call)
   * </pre>
   *
   * Protobuf type {@code pbui_Type_meetQueryPublicInfo}
   */
  public  static final class pbui_Type_meetQueryPublicInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_meetQueryPublicInfo, pbui_Type_meetQueryPublicInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_meetQueryPublicInfo)
      pbui_Type_meetQueryPublicInfoOrBuilder {
    private pbui_Type_meetQueryPublicInfo() {
      dataid_ = emptyIntList();
    }
    public static final int DATAID_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList dataid_;
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getDataidList() {
      return dataid_;
    }
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    public int getDataidCount() {
      return dataid_.size();
    }
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    public int getDataid(int index) {
      return dataid_.getInt(index);
    }
    private void ensureDataidIsMutable() {
      if (!dataid_.isModifiable()) {
        dataid_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(dataid_);
       }
    }
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    private void setDataid(
        int index, int value) {
      ensureDataidIsMutable();
      dataid_.setInt(index, value);
    }
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    private void addDataid(int value) {
      ensureDataidIsMutable();
      dataid_.addInt(value);
    }
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    private void addAllDataid(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDataidIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, dataid_);
    }
    /**
     * <pre>
     *要查询的项
     * </pre>
     *
     * <code>repeated fixed32 dataid = 1;</code>
     */
    private void clearDataid() {
      dataid_ = emptyIntList();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dataid_.size(); i++) {
        output.writeFixed32(1, dataid_.getInt(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getDataidList().size();
        size += dataSize;
        size += 1 * getDataidList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *查询系统全局字串
     *call
     *TYPE_MEET_INTERFACE_PUBLICINFO
     *method:notify/query(call)
     * </pre>
     *
     * Protobuf type {@code pbui_Type_meetQueryPublicInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_meetQueryPublicInfo)
        com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getDataidList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataidList());
      }
      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public int getDataidCount() {
        return instance.getDataidCount();
      }
      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public int getDataid(int index) {
        return instance.getDataid(index);
      }
      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public Builder setDataid(
          int index, int value) {
        copyOnWrite();
        instance.setDataid(index, value);
        return this;
      }
      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public Builder addDataid(int value) {
        copyOnWrite();
        instance.addDataid(value);
        return this;
      }
      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public Builder addAllDataid(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        copyOnWrite();
        instance.addAllDataid(values);
        return this;
      }
      /**
       * <pre>
       *要查询的项
       * </pre>
       *
       * <code>repeated fixed32 dataid = 1;</code>
       */
      public Builder clearDataid() {
        copyOnWrite();
        instance.clearDataid();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_meetQueryPublicInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          dataid_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo other = (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo) arg1;
          dataid_= visitor.visitIntList(dataid_, other.dataid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {
                  if (!dataid_.isModifiable()) {
                    dataid_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(dataid_);
                  }
                  dataid_.addInt(input.readFixed32());
                  break;
                }
                case 10: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!dataid_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    final int currentSize = dataid_.size();
                    dataid_ = dataid_.mutableCopyWithCapacity(
                        currentSize + (length/4));
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    dataid_.addInt(input.readFixed32());
                  }
                  input.popLimit(limit);
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_meetQueryPublicInfo)
    private static final com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_meetQueryPublicInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetQueryPublicInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_meetQueryPublicInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_meetQueryPublicInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Item_meetPublicInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_meetPublicInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *字串ID
     * </pre>
     *
     * <code>optional fixed32 dataid = 1;</code>
     */
    int getDataid();

    /**
     * <pre>
     *最大长度 MEET_PUBLICINFO_DATALEN=260;
     * </pre>
     *
     * <code>optional bytes dataval = 2;</code>
     */
    com.google.protobuf.ByteString getDataval();
  }
  /**
   * <pre>
   *返回查询系统全局字串
   *单个全局字串
   * </pre>
   *
   * Protobuf type {@code pbui_Item_meetPublicInfo}
   */
  public  static final class pbui_Item_meetPublicInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_meetPublicInfo, pbui_Item_meetPublicInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_meetPublicInfo)
      pbui_Item_meetPublicInfoOrBuilder {
    private pbui_Item_meetPublicInfo() {
      dataval_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int DATAID_FIELD_NUMBER = 1;
    private int dataid_;
    /**
     * <pre>
     *字串ID
     * </pre>
     *
     * <code>optional fixed32 dataid = 1;</code>
     */
    public int getDataid() {
      return dataid_;
    }
    /**
     * <pre>
     *字串ID
     * </pre>
     *
     * <code>optional fixed32 dataid = 1;</code>
     */
    private void setDataid(int value) {
      
      dataid_ = value;
    }
    /**
     * <pre>
     *字串ID
     * </pre>
     *
     * <code>optional fixed32 dataid = 1;</code>
     */
    private void clearDataid() {
      
      dataid_ = 0;
    }

    public static final int DATAVAL_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dataval_;
    /**
     * <pre>
     *最大长度 MEET_PUBLICINFO_DATALEN=260;
     * </pre>
     *
     * <code>optional bytes dataval = 2;</code>
     */
    public com.google.protobuf.ByteString getDataval() {
      return dataval_;
    }
    /**
     * <pre>
     *最大长度 MEET_PUBLICINFO_DATALEN=260;
     * </pre>
     *
     * <code>optional bytes dataval = 2;</code>
     */
    private void setDataval(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataval_ = value;
    }
    /**
     * <pre>
     *最大长度 MEET_PUBLICINFO_DATALEN=260;
     * </pre>
     *
     * <code>optional bytes dataval = 2;</code>
     */
    private void clearDataval() {
      
      dataval_ = getDefaultInstance().getDataval();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataid_ != 0) {
        output.writeFixed32(1, dataid_);
      }
      if (!dataval_.isEmpty()) {
        output.writeBytes(2, dataval_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (dataid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, dataid_);
      }
      if (!dataval_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dataval_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *返回查询系统全局字串
     *单个全局字串
     * </pre>
     *
     * Protobuf type {@code pbui_Item_meetPublicInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_meetPublicInfo)
        com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *字串ID
       * </pre>
       *
       * <code>optional fixed32 dataid = 1;</code>
       */
      public int getDataid() {
        return instance.getDataid();
      }
      /**
       * <pre>
       *字串ID
       * </pre>
       *
       * <code>optional fixed32 dataid = 1;</code>
       */
      public Builder setDataid(int value) {
        copyOnWrite();
        instance.setDataid(value);
        return this;
      }
      /**
       * <pre>
       *字串ID
       * </pre>
       *
       * <code>optional fixed32 dataid = 1;</code>
       */
      public Builder clearDataid() {
        copyOnWrite();
        instance.clearDataid();
        return this;
      }

      /**
       * <pre>
       *最大长度 MEET_PUBLICINFO_DATALEN=260;
       * </pre>
       *
       * <code>optional bytes dataval = 2;</code>
       */
      public com.google.protobuf.ByteString getDataval() {
        return instance.getDataval();
      }
      /**
       * <pre>
       *最大长度 MEET_PUBLICINFO_DATALEN=260;
       * </pre>
       *
       * <code>optional bytes dataval = 2;</code>
       */
      public Builder setDataval(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDataval(value);
        return this;
      }
      /**
       * <pre>
       *最大长度 MEET_PUBLICINFO_DATALEN=260;
       * </pre>
       *
       * <code>optional bytes dataval = 2;</code>
       */
      public Builder clearDataval() {
        copyOnWrite();
        instance.clearDataval();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_meetPublicInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo other = (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo) arg1;
          dataid_ = visitor.visitInt(dataid_ != 0, dataid_,
              other.dataid_ != 0, other.dataid_);
          dataval_ = visitor.visitByteString(dataval_ != com.google.protobuf.ByteString.EMPTY, dataval_,
              other.dataval_ != com.google.protobuf.ByteString.EMPTY, other.dataval_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  dataid_ = input.readFixed32();
                  break;
                }
                case 18: {

                  dataval_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_meetPublicInfo)
    private static final com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_meetPublicInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_meetPublicInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_meetPublicInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_meetPublicInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_meetPublicInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo> 
        getItemList();
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo getItem(int index);
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    int getItemCount();
  }
  /**
   * <pre>
   *call
   *TYPE_MEET_INTERFACE_PUBLICINFO
   *method:set/query(return)
   * </pre>
   *
   * Protobuf type {@code pbui_Type_meetPublicInfo}
   */
  public  static final class pbui_Type_meetPublicInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_meetPublicInfo, pbui_Type_meetPublicInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_meetPublicInfo)
      pbui_Type_meetPublicInfoOrBuilder {
    private pbui_Type_meetPublicInfo() {
      item_ = emptyProtobufList();
    }
    public static final int ITEM_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo> item_;
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfoOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfoOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    private void ensureItemIsMutable() {
      if (!item_.isModifiable()) {
        item_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
       }
    }

    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void addItem(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(value);
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void addItem(
        com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void addAllItem(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo> values) {
      ensureItemIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, item_);
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void clearItem() {
      item_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
     */
    private void removeItem(int index) {
      ensureItemIsMutable();
      item_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *call
     *TYPE_MEET_INTERFACE_PUBLICINFO
     *method:set/query(return)
     * </pre>
     *
     * Protobuf type {@code pbui_Type_meetPublicInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_meetPublicInfo)
        com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo> getItemList() {
        return java.util.Collections.unmodifiableList(
            instance.getItemList());
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }/**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo getItem(int index) {
        return instance.getItem(index);
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo value) {
        copyOnWrite();
        instance.setItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder addItem(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo value) {
        copyOnWrite();
        instance.addItem(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo value) {
        copyOnWrite();
        instance.addItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder addItem(
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo> values) {
        copyOnWrite();
        instance.addAllItem(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder clearItem() {
        copyOnWrite();
        instance.clearItem();
        return this;
      }
      /**
       * <code>repeated .pbui_Item_meetPublicInfo item = 1;</code>
       */
      public Builder removeItem(int index) {
        copyOnWrite();
        instance.removeItem(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_meetPublicInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          item_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo other = (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo) arg1;
          item_= visitor.visitList(item_, other.item_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!item_.isModifiable()) {
                    item_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
                  }
                  item_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Item_meetPublicInfo.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_meetPublicInfo)
    private static final com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_meetPublicInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_meetPublicInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_meetPublicInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_meetPublicInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_MeetPublicInfoPropertyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_MeetPublicInfoProperty)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *数据ID Pb_PublicPropertyId
     * </pre>
     *
     * <code>optional fixed32 propertyid = 1;</code>
     */
    int getPropertyid();

    /**
     * <pre>
     *传入参数
     * </pre>
     *
     * <code>optional fixed32 parameterval = 2;</code>
     */
    int getParameterval();
  }
  /**
   * <pre>
   *method: queryproperty
   * </pre>
   *
   * Protobuf type {@code pbui_Type_MeetPublicInfoProperty}
   */
  public  static final class pbui_Type_MeetPublicInfoProperty extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_MeetPublicInfoProperty, pbui_Type_MeetPublicInfoProperty.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_MeetPublicInfoProperty)
      pbui_Type_MeetPublicInfoPropertyOrBuilder {
    private pbui_Type_MeetPublicInfoProperty() {
    }
    public static final int PROPERTYID_FIELD_NUMBER = 1;
    private int propertyid_;
    /**
     * <pre>
     *数据ID Pb_PublicPropertyId
     * </pre>
     *
     * <code>optional fixed32 propertyid = 1;</code>
     */
    public int getPropertyid() {
      return propertyid_;
    }
    /**
     * <pre>
     *数据ID Pb_PublicPropertyId
     * </pre>
     *
     * <code>optional fixed32 propertyid = 1;</code>
     */
    private void setPropertyid(int value) {
      
      propertyid_ = value;
    }
    /**
     * <pre>
     *数据ID Pb_PublicPropertyId
     * </pre>
     *
     * <code>optional fixed32 propertyid = 1;</code>
     */
    private void clearPropertyid() {
      
      propertyid_ = 0;
    }

    public static final int PARAMETERVAL_FIELD_NUMBER = 2;
    private int parameterval_;
    /**
     * <pre>
     *传入参数
     * </pre>
     *
     * <code>optional fixed32 parameterval = 2;</code>
     */
    public int getParameterval() {
      return parameterval_;
    }
    /**
     * <pre>
     *传入参数
     * </pre>
     *
     * <code>optional fixed32 parameterval = 2;</code>
     */
    private void setParameterval(int value) {
      
      parameterval_ = value;
    }
    /**
     * <pre>
     *传入参数
     * </pre>
     *
     * <code>optional fixed32 parameterval = 2;</code>
     */
    private void clearParameterval() {
      
      parameterval_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (propertyid_ != 0) {
        output.writeFixed32(1, propertyid_);
      }
      if (parameterval_ != 0) {
        output.writeFixed32(2, parameterval_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (propertyid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, propertyid_);
      }
      if (parameterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, parameterval_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *method: queryproperty
     * </pre>
     *
     * Protobuf type {@code pbui_Type_MeetPublicInfoProperty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_MeetPublicInfoProperty)
        com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *数据ID Pb_PublicPropertyId
       * </pre>
       *
       * <code>optional fixed32 propertyid = 1;</code>
       */
      public int getPropertyid() {
        return instance.getPropertyid();
      }
      /**
       * <pre>
       *数据ID Pb_PublicPropertyId
       * </pre>
       *
       * <code>optional fixed32 propertyid = 1;</code>
       */
      public Builder setPropertyid(int value) {
        copyOnWrite();
        instance.setPropertyid(value);
        return this;
      }
      /**
       * <pre>
       *数据ID Pb_PublicPropertyId
       * </pre>
       *
       * <code>optional fixed32 propertyid = 1;</code>
       */
      public Builder clearPropertyid() {
        copyOnWrite();
        instance.clearPropertyid();
        return this;
      }

      /**
       * <pre>
       *传入参数
       * </pre>
       *
       * <code>optional fixed32 parameterval = 2;</code>
       */
      public int getParameterval() {
        return instance.getParameterval();
      }
      /**
       * <pre>
       *传入参数
       * </pre>
       *
       * <code>optional fixed32 parameterval = 2;</code>
       */
      public Builder setParameterval(int value) {
        copyOnWrite();
        instance.setParameterval(value);
        return this;
      }
      /**
       * <pre>
       *传入参数
       * </pre>
       *
       * <code>optional fixed32 parameterval = 2;</code>
       */
      public Builder clearParameterval() {
        copyOnWrite();
        instance.clearParameterval();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_MeetPublicInfoProperty)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty other = (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty) arg1;
          propertyid_ = visitor.visitInt(propertyid_ != 0, propertyid_,
              other.propertyid_ != 0, other.propertyid_);
          parameterval_ = visitor.visitInt(parameterval_ != 0, parameterval_,
              other.parameterval_ != 0, other.parameterval_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  propertyid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  parameterval_ = input.readFixed32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_MeetPublicInfoProperty)
    private static final com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_MeetPublicInfoProperty();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoProperty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_MeetPublicInfoProperty> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_MeetPublicInfoProperty> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_MeetPublicInfoPropertyValOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_MeetPublicInfoPropertyVal)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional fixed32 intval = 1;</code>
     */
    int getIntval();

    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional bytes textval = 2;</code>
     */
    com.google.protobuf.ByteString getTextval();
  }
  /**
   * <pre>
   *method: queryproperty
   * </pre>
   *
   * Protobuf type {@code pbui_Type_MeetPublicInfoPropertyVal}
   */
  public  static final class pbui_Type_MeetPublicInfoPropertyVal extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_MeetPublicInfoPropertyVal, pbui_Type_MeetPublicInfoPropertyVal.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_MeetPublicInfoPropertyVal)
      pbui_Type_MeetPublicInfoPropertyValOrBuilder {
    private pbui_Type_MeetPublicInfoPropertyVal() {
      textval_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int INTVAL_FIELD_NUMBER = 1;
    private int intval_;
    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional fixed32 intval = 1;</code>
     */
    public int getIntval() {
      return intval_;
    }
    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional fixed32 intval = 1;</code>
     */
    private void setIntval(int value) {
      
      intval_ = value;
    }
    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional fixed32 intval = 1;</code>
     */
    private void clearIntval() {
      
      intval_ = 0;
    }

    public static final int TEXTVAL_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString textval_;
    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional bytes textval = 2;</code>
     */
    public com.google.protobuf.ByteString getTextval() {
      return textval_;
    }
    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional bytes textval = 2;</code>
     */
    private void setTextval(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      textval_ = value;
    }
    /**
     * <pre>
     *根据属性ID判断使用
     * </pre>
     *
     * <code>optional bytes textval = 2;</code>
     */
    private void clearTextval() {
      
      textval_ = getDefaultInstance().getTextval();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intval_ != 0) {
        output.writeFixed32(1, intval_);
      }
      if (!textval_.isEmpty()) {
        output.writeBytes(2, textval_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (intval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, intval_);
      }
      if (!textval_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, textval_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *method: queryproperty
     * </pre>
     *
     * Protobuf type {@code pbui_Type_MeetPublicInfoPropertyVal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_MeetPublicInfoPropertyVal)
        com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyValOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *根据属性ID判断使用
       * </pre>
       *
       * <code>optional fixed32 intval = 1;</code>
       */
      public int getIntval() {
        return instance.getIntval();
      }
      /**
       * <pre>
       *根据属性ID判断使用
       * </pre>
       *
       * <code>optional fixed32 intval = 1;</code>
       */
      public Builder setIntval(int value) {
        copyOnWrite();
        instance.setIntval(value);
        return this;
      }
      /**
       * <pre>
       *根据属性ID判断使用
       * </pre>
       *
       * <code>optional fixed32 intval = 1;</code>
       */
      public Builder clearIntval() {
        copyOnWrite();
        instance.clearIntval();
        return this;
      }

      /**
       * <pre>
       *根据属性ID判断使用
       * </pre>
       *
       * <code>optional bytes textval = 2;</code>
       */
      public com.google.protobuf.ByteString getTextval() {
        return instance.getTextval();
      }
      /**
       * <pre>
       *根据属性ID判断使用
       * </pre>
       *
       * <code>optional bytes textval = 2;</code>
       */
      public Builder setTextval(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTextval(value);
        return this;
      }
      /**
       * <pre>
       *根据属性ID判断使用
       * </pre>
       *
       * <code>optional bytes textval = 2;</code>
       */
      public Builder clearTextval() {
        copyOnWrite();
        instance.clearTextval();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_MeetPublicInfoPropertyVal)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal other = (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal) arg1;
          intval_ = visitor.visitInt(intval_ != 0, intval_,
              other.intval_ != 0, other.intval_);
          textval_ = visitor.visitByteString(textval_ != com.google.protobuf.ByteString.EMPTY, textval_,
              other.textval_ != com.google.protobuf.ByteString.EMPTY, other.textval_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  intval_ = input.readFixed32();
                  break;
                }
                case 18: {

                  textval_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_MeetPublicInfoPropertyVal)
    private static final com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_MeetPublicInfoPropertyVal();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfacePublicinfo.pbui_Type_MeetPublicInfoPropertyVal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_MeetPublicInfoPropertyVal> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_MeetPublicInfoPropertyVal> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
