syntax = "proto3";
option java_package = "com.mogujie.tt.protobuf";
option optimize_for = LITE_RUNTIME;

import "Interface_Macro.proto";

//a代表密码过期的日期 231218
//b代表备注内容
//c代表权限
//已经使用40字节,备注内容最多使用50字节
//comment -->c 权限
enum Pb_AdminRight 
{
Pb_ADMIN_PERFLAG_ZERO=0;//
Pb_ADMIN_PERFLAG_DEVICE=		0x00000001; //设备管理
Pb_ADMIN_PERFLAG_DEVICECTL=		0x00000002; //设备控制
Pb_ADMIN_PERFLAG_ROOM=			0x00000004; //会议室管理
Pb_ADMIN_PERFLAG_PEOPLE=		0x00000008; //常用人员管理
Pb_ADMIN_PERFLAG_FACE=			0x00000010; //界面配置
Pb_ADMIN_PERFLAG_MEET=			0x00000020; //会议管理
Pb_ADMIN_PERFLAG_LOG=			0x00000040; //日志查看
Pb_ADMIN_PERFLAG_MEETDATA=		0x00000080; //会议资料管理
}
message pbui_Item_AdminDetailInfo
{
	fixed32 adminid=1;
	bytes   adminname=2;
	bytes   pw=3;//密码 md5 ascill 32字节
	bytes   comment=4;//{"a":"231218","b":"xx","c":"0x00000001"}
	bytes   phone=5;
	bytes   email=6;
}

//管理员
//call
//Pb_TYPE_MEET_INTERFACE_ADMIN
//method: add\del\modify\query
message pbui_TypeAdminDetailInfo
{
	repeated pbui_Item_AdminDetailInfo  item=1;// 
}

//修改管理员自身的密码
//call
//Pb_TYPE_MEET_INTERFACE_ADMIN
//method: set
message pbui_Type_AdminModifyPwd
{
	bytes			adminname=1;//用户名
	bytes			adminoldpwd=2;//用户密码(ascill/md5ascill)
	bytes			adminnewpwd=3;//用户密码(ascill/md5ascill)
}

//管理员登陆
//Pb_TYPE_MEET_INTERFACE_ADMIN
//method: logon
message pbui_Type_AdminLogon
{
	fixed32			isascill=1;//=0md5字符密码 =1明文密码
	bytes			adminname=2;//用户名 常用人员手机号
	bytes			adminpwd=3;//用户密码(ascill/md5ascill)
	fixed32			logonmode=4;//=0管理员登陆 =1常用人员登陆 =2离线本地模式
}

//登陆返回
//Pb_TYPE_MEET_INTERFACE_ADMIN
//method: logon
message pbui_Type_AdminLogonStatus
{
	fixed32			err=1;// 参见 Pb_AdminLogonStatus
	fixed32			sessionid=2;//会话ID
	fixed32			adminid=3;//会话ID
	bytes			adminname=4;
	fixed32         errnums=5; //密码累计错误次数
	fixed32         lockseconds=6; //密码锁定剩余秒数	
}

//会议管理员控制的会场
//type:Pb_TYPE_MEET_INTERFACE_MANAGEROOM
//method: query/save
message pbui_Type_MeetManagerRoomDetailInfo
{
	fixed32   mgrid=1;//管理员ID
	repeated  fixed32 roomid=2; //会场ID
}

//查询指定管理人员的某项属性
//property id
enum Pb_AdminPropertyId 
{
Pb_ADMIN_PROPERTY_ZERO=0;//
Pb_ADMIN_PROPERTY_NAME=					1; //名称 query(string)
Pb_ADMIN_PROPERTY_ALLCOMMENT=			2; //完整备注 query(string)
Pb_ADMIN_PROPERTY_PHONE=				3; //电话 query(string)
Pb_ADMIN_PROPERTY_EMAIL=				4; //邮箱 query(string)
Pb_ADMIN_PROPERTY_PASSWORD=				5; //密码 query(string)
Pb_ADMIN_PROPERTY_RIGHT=				6; //权限 query(int32u)
Pb_ADMIN_PROPERTY_PSWDATE=				7; //到期日期 query(string)
Pb_ADMIN_PROPERTY_COMMENT=				8; //解释后的备注 query(string)
}

//method: queryproperty
message pbui_Type_AdminPropertyQuery
{
	fixed32 propertyid=1;//数据ID
	fixed32 adminid=2;//传入指定管理员id, 0表示当前登陆的管理员id
	fixed32 parameterval=3;//传入参数 
}

//method: queryproperty
message pbui_Type_AdminPropertyQueryReturn
{ 
	fixed32 propertyval=1;//返回值
	bytes   propertytext=2;//字符串
}

enum Pb_ADMINMUTILFLAG 
{
Pb_MEET_MUTILADMIN_FLAG_ZERO=0;
Pb_MEET_MUTILADMIN_FLAG_DELALL= 0x00000001; //导入前删除人员
}

//批量操作管理员
//TYPE_MEET_INTERFACE_ADMIN
//method:SUBMIT|delall
message pbui_Type_MutilAdminOper
{
	fixed32 flag=1;//Pb_MEET_MUTILADMIN_FLAG_DELALL
	bytes json=2;
	/*
	{
	"data":  //
	[
	{
	"name::"adminct",
	"phone":"",
	"email":"",
	"comment":"",
	"password":"",//密码 md5 ascill 32字节 为空默认是123456
	"adminid":"",//dellall方法时设置
	}
	]
	}
	*/
}