syntax = "proto3";
option java_package = "com.mogujie.tt.protobuf";
option optimize_for = LITE_RUNTIME;

import "Interface_Macro.proto";

//收到消息确认的回复
//callback / call
//type:Pb_TYPE_MEET_INTERFACE_MEETIM
//method: Pb_METHOD_MEET_INTERFACE_SUBMIT
message pbui_Type_MeetIMConfirm
{
	//原消息的数据
	fixed32		meetid=1;//会议ID
	fixed32	    msgtype=2;//消息类型
	fixed64	    utcsecond=3;//UTC时间 单位：UTC 秒
	fixed32		role=4;//原发送者角色
	fixed32	    memberid=5;//原发送者ID
	fixed32		senddevid=6;//原发送的设备ID

	bytes		confirmmsg=7;//确认的消息文本
	fixed64	    confirmutcsecond=8;//确认的UTC时间 单位：UTC 秒  -- 发送时库赋值
	fixed32		confirmdevid=9;//确认的设备ID -- 发送时库赋值
	bytes		confirmseatename=10;//确认席位名  -- 发送时库赋值
}

//收到新的会议交流信息
//callback
//type:Pb_TYPE_MEET_INTERFACE_MEETIM
//method: notify
message pbui_Type_MeetIM
{
	fixed32		meetid=1;//会议ID
	fixed32	    msgtype=2;//消息类型 参见 Pb_MeetIMMSG_TYPE
	fixed32		role=3;//发送者角色 参见 Pb_MeetMemberRole
	fixed32	    memberid=4;//发送者ID
	fixed32	    senddeviceid=5;//发送者ID
	bytes		msg=6;//消息文本 长度 Pb_MEETIM_CHAR_MSG_MAXLEN
	fixed64	    utcsecond=7;//发送UTC时间 单位:秒

	bytes		meetname=8;//会议名称
	bytes		roomname=9;//会议室名
	bytes		membername=10;//人员名称
	bytes		seatename=11;//席位名
	
	repeated fixed32      userids=12; //为0表示当前会议全部 如果是会议服务类请求为0
}

//发送消息
//call
//type:Pb_TYPE_MEET_INTERFACE_MEETIM
//method: send
message pbui_Type_SendMeetIM
{
	fixed32	    msgtype=1;//消息类型 参见 Pb_MeetIMMSG_TYPE
	bytes		msg=2;//消息文本  长度 Pb_MEETIM_CHAR_MSG_MAXLEN
	repeated fixed32      userids=3; //为0表示当前会议全部 如果是会议服务类请求为0
}

//会议交流信息
message pbui_Item_MeetIMDetailInfo
{
	fixed32		meetid=1;//会议ID
	fixed32	    msgtype =2;//消息类型 参见 Pb_MeetIMMSG_TYPE
	fixed32		role=3;//发送者角色
	fixed32	    memberid=4;//发送者ID
	fixed32	    senddeviceid=5;//发送者ID
	bytes		msg=6;//消息文本 长度 Pb_MEETIM_CHAR_MSG_MAXLEN
	fixed64	    utcsecond=7;//发送UTC时间 单位:秒
	
	bytes		confirmmsg=8;//确认的消息文本
	fixed64	    confirmutcsecond=9;//确认的UTC时间 单位：UTC 秒
	fixed32		confirmdevid=10;//确认的设备ID
	bytes		confirmseatename=11;//确认席位名
	
	repeated fixed32      userids=12; //为0表示当前会议全部 如果是会议服务类请求为0
}

//callreturn
//type:Pb_TYPE_MEET_INTERFACE_MEETIM
//method: query
message pbui_Type_MeetIMDetailInfo
{
	repeated pbui_Item_MeetIMDetailInfo item=1;
}

//组合查询
//type:Pb_TYPE_MEET_INTERFACE_MEETIM
//method: complexquery
message pbui_Type_MeetComplexQueryIM
{
	fixed32      queryflag=1; //查询标志 参见 Pb_COMPLEXQUERY_ZERO

	fixed32	    msgtype=2;//消息类型
	fixed32		role=3;//发送者角色
	fixed32	    memberid=4;//发送者ID

	//时间范围
	fixed64	    startutcsecond=5;//发送UTC时间
	fixed64	    endutcsecond=6;//发送UTC时间

	fixed32			pageindex=7;//起始索引 从0 开始
	fixed32			pagenum=8;//每页项数
}

//组合查询返回结构头部
//callreturn
//type:Pb_TYPE_MEET_INTERFACE_MEETIM
//method: complexpagequery
message pbui_TypePageResQueryrMsgInfo
{
	fixed32			pageindex=1;//起始索引 从0 开始
	fixed32			pagenum=2;//每页项数
	fixed32			itemnum=3;//当前页项数 ,根据数据不同用不同的解析
	fixed32			totalnum=4;//总项数
	
	repeated pbui_Item_MeetIMDetailInfo item =5;//消息
}