syntax = "proto3";
option java_package = "com.mogujie.tt.protobuf";
option optimize_for = LITE_RUNTIME;

import "Interface_Macro.proto";

//参会人员
message pbui_Item_MemberDetailInfo
{
	fixed32 personid=1;
	bytes   name=2;
	bytes   company=3;
	bytes   job=4;
	bytes   comment=5;
	bytes   phone=6;
	bytes   email=7;
	bytes   password=8;
	fixed32 role=9;//查询参会人时会返回参会人员的角色 需要提前缓存席位绑定的数据 参见Interface_Macro.proto Pb_MeetMemberRole
}

//参会人员
//call callreturn
//type:Pb_TYPE_MEET_INTERFACE_MEMBER
//method: add\del\modify\query
message pbui_Type_MemberDetailInfo
{
	repeated pbui_Item_MemberDetailInfo item=1;
}
enum Pb_MeetSMSOper
{
Pb_MEET_SMS_OPERTEMP_START=  0;//=会议通知
Pb_MEET_SMS_OPERTEMP_LATE=   1;//=会议延期
Pb_MEET_SMS_OPERTEMP_CANCLE= 2;//=会议取消
Pb_MEET_SMS_OPERTEMP_NORMAL= 3;//=普通文本
Pb_MEET_SMS_OPERTEMP_APPROVAL=	4;//=审批催促

}

//短信通知会议
//call
//type：TYPE_MEET_INTERFACE_MEMBER
//fun: FUN_All 会议短信通知
//method:METHOD_MEET_INTERFACE_NOTIFY
message pbui_Type_MeetSMSNotify
{
	fixed32 meetid=1;//可以指定会议发送通知 为0表示当前会议
	fixed32 templateindex=2;//参见Pb_MeetSMSOper的定义 需要指定模板，后台会根据模板去发送
	bytes   msg=3;//如果后台没有设置模板ID，则会优先发送用户提交的消息,如果用户没有提交，则会发送一条默认的消息 目前只有中国移动平台支持
}

//memberdetailflag
//错误码
enum Pb_MemberDetailFlag
{
Pb_MEMBERDETAIL_FLAG_ZERO=0;
Pb_MEMBERDETAIL_FLAG_ONLINE= 0x00000001; //是否在线
}

//参会人员详细信息
message pbui_Item_MeetMemberDetailInfo
{
	fixed32 devid=1;//设备ID
	bytes   devname=2;//设备名称
	fixed32 memberdetailflag=3;//标志 参见本文件的 Pb_MemberDetailFlag 定义
	fixed32 facestatus=4;//界面状态 参见Interface_Macro.proto Pb_MemState_MainFace 定义
	fixed32 memberid=5;//参会人员ID
	bytes   membername=6;//参会人员名称
	bytes   company=7;
	bytes   job=8;
	bytes   comment=9;
	bytes   phone=10;
	bytes   email=11;
	bytes   password=12;
	fixed32 permission=13;//参会人员权限 参见Interface_Macro.proto  Pb_MemberPermissionPropertyID 定义
	fixed32 role=14;//查询参会人时会返回参会人员的角色 需要提前缓存席位绑定的数据 参见Interface_Macro.proto Pb_MeetMemberRole
	fixed32 encryptlevel=15;// 占用permission的高4位
}

enum Pb_MemberImportFlag
{
Pb_MEET_IMPORT_MEET_FLAG_ZERO =0;
Pb_MEET_IMPORT_MEET_FLAG_DELALLMEM=0x00000001; //导入前清空参会人员并关联删除签到，座位绑定等关联数据
}

//导入参会人员
//call
//method: submit
message pbui_Type_MemberImport
{
	fixed32 flag=1;//Pb_MemberImportFlag MEET_IMPORT_MEET_FLAG_DELALLMEM

	bytes   json=2;
	/*
	{
	"member":  //
	[
	{
	"name::"陈工",
	"company":"xx",
	"job":"xx",
	"phone":"123456",
	"email":"",
	"comment":"",
	"password":"123456",
	"memid":"",//服务器设置客户端提交不用设置
	"devid":"",//指定设备绑定时设置
	"perm":"",//指定权限时设置
	"role":"",//指定角色时设置
	}
	]
	}
	*/
}

//excludetype
enum Pb_MemExcludeFlag
{
Pb_MEM_QUERYFLAG_ZERO=0;//不使用
Pb_MEM_QUERYFLAG_NOTABLEDEV=		0x00000001; //去掉绑定在桌牌的人员
Pb_MEM_QUERYFLAG_NOOFFLINE=			0x00000002; //去掉离线的人员
Pb_MEM_QUERYFLAG_NOONLINE=			0x00000004; //去掉在线的人员
Pb_MEM_QUERYFLAG_NOMEETFACE=	    0x00000008; //去掉在会议界面的人员
Pb_MEM_QUERYFLAG_NOCOMMONFACE=   	0x00000010; //去掉主界面的人员
Pb_MEM_QUERYFLAG_NOSEAT=		    0x00000020; //去掉没有席位绑定的人员
}

//获取参会人员详细信息,注：需要缓存参会人、参会人权限、排位数据
//call
//type: TYPE_MEET_INTERFACE_MEMBER
//method: METHOD_MEET_INTERFACE_DETAILINFO
message pbui_Type_MeetMemberDetailInfo
{
	fixed32     excludetype=1;//Pb_MemExcludeFlag
	repeated pbui_Item_MeetMemberDetailInfo item=2;
}

//二维码内容：{"meetid":"1","roomid":"1"}
//扫码加入会议
//call
//type:Pb_TYPE_MEET_INTERFACE_MEMBER
//method: enter
message pbui_Type_ScanEnterMeet
{
	fixed32 meetingid=1;//扫码加入的会议ID
	fixed32 memberrole=2;//参会人角色 参见Pb_MeetMemberRole
	pbui_Item_MemberDetailInfo memberinfo=3;//参会人员的信息,如果参会人ID不为0，表示新建一个参会人员

}

//快速入会
//type:TYPE_MEET_INTERFACE_MEMBER
//method: METHOD_MEET_INTERFACE_START
message pbui_Type_FastEnterMeet
{
	fixed32 meetid =1;
	fixed32 deviceid=2;//为0表示本机设备
	bytes   phone=3;  //电话

	//预留数据后面可能会进行使用 暂时不使用
	bytes  jsontext=4; 
}

//参会人员属性
//call
//type:Pb_TYPE_MEET_INTERFACE_MEMBER
//method: queryproperty
message pbui_Type_MeetMemberQueryProperty
{
	fixed32 propertyid=1;//属性ID 参见 Pb_MemberPropertyID
	fixed32 parameterval=2;//传入参数 为0表示本机设置定的人员id
}

//参会人员属性
//callreturn
//type: Pb_TYPE_MEET_INTERFACE_MEMBER
//method: queryproperty
message pbui_Type_MeetMembeProperty
{
	fixed32 propertyval=1;//整数属性值 参见属性ID的类型定义
	bytes   propertytext=2;//字符串属性值
}

//修改参会人员排序
//call
//method: Pb_TYPE_MEET_INTERFACE_MEMBER
//method: Pb_METHOD_MEET_INTERFACE_CONTROL|Pb_METHOD_MEET_INTERFACE_DELALL
message pbui_Type_ModifyMemberPos
{
	repeated fixed32 memberid=1;//按ID排序
}

//参会人员权限
message pbui_Item_MemberPermission
{
	fixed32 memberid=1;//参会人ID
	fixed32 permission=2;	//参会人权限
	fixed32 encryptlevel=3; //占用permission的高4位
}

//参会人员权限
//type:Pb_TYPE_MEET_INTERFACE_MEMBERPERMISSION
//call
//method: save\query
message pbui_Type_MemberPermission
{
	repeated pbui_Item_MemberPermission item=1;
}

//参会人权限
//property id
enum Pb_MemPermProID
{
Pb_MEETMEMBERPERMISSION_PROPERTY_ZERO=	0; //占位
Pb_MEETMEMBERPERMISSION_PROPERTY_ALLPERMISSIONS=	1; //所有权限 query
Pb_MEETMEMBERPERMISSION_PROPERTY_SCREEN=			2; //同屏权限 query
Pb_MEETMEMBERPERMISSION_PROPERTY_PROJECTIVE=		3; //投影权限 query
Pb_MEETMEMBERPERMISSION_PROPERTY_UPLOAD=			4; //上传权限 query
Pb_MEETMEMBERPERMISSION_PROPERTY_DOWNLOAD=			5; //下载权限 query
Pb_MEETMEMBERPERMISSION_PROPERTY_VOTE=				6; //投票权限 query
Pb_MEETMEMBERPERMISSION_PROPERTY_LEVEL=				7; //保密级别 query
}

//参会人员权限
//call
//type:Pb_TYPE_MEET_INTERFACE_MEMBERPERMISSION
//method: queryproperty
message pbui_Type_MeetMemberPermissionQueryProperty
{
	fixed32 propertyid=1;//属性ID 参见 Pb_MemPermProID
	fixed32 memberid=2;//传入参数 为0表示本机设置定的人员id
}

//参会人员权限
//type:Pb_TYPE_MEET_INTERFACE_MEMBERPERMISSION
//callreturn
//method: queryproperty
message pbui_Type_MemberPermissionProperty
{
	fixed32 propertyval=1;//整数属性值
}

//参会人员分组
message pbui_Item_MemberGroupDetailInfo
{
	fixed32 groupid=1;
	bytes   name=2;
}

//参会人员分组
//type:Pb_TYPE_MEET_INTERFACE_MEMBERGROUP
//call
//method: add\del\modify\query
message pbui_Type_MemberGroupDetailInfo
{
	repeated pbui_Item_MemberGroupDetailInfo item=1;
}

//参会人员分组人员
//type:Pb_TYPE_MEET_INTERFACE_MEMBERGROUPITEM
//call
//method: save\query
message pbui_Type_MemberInGroupDetailInfo
{
	fixed32			groupid=1;
	repeated fixed32 memberid=2;
}